# Hindamine

Et me teaksime, mida sa tead ja oskad, viime alguses läbi lähtetesti, milles on ülesanded suureneva keerukuse järjekorras. Selles testis tuleb sul nii palju ülesandeid lahendada, kui oskad. Vastavalt testi tulemustele kehtestan igale õpilasele individuaalse õpijärje. Sama õpijärjega õpilased hakkavad õppima koos.

Hindan iga õpiväljundi saavutatust õppeprotsessi käigus kohapeal.

Kokkuvõttev hindamine toimub iga trimestri lõpus testiga, milles on õpilasele ülesanded vaid õpiväljundite kohta, mida ta on seni saavutanud. Pakun välja selleks kontrolltööks kolm päeva, millest õpilane valib ühe ja ülejäänud päevades õpib edasi või harjutab õpitut. Õpperuumi sisenedes paigutab õpilane kõik üleliigsed kaasavõetud asjad tagaruumi ning suundub ainult kirjutusvahendiga laua juurde, millel on tema nimi. Üleliigse esemega õpilane kontrolltöö sooritamist alustada ei saa, muul juhul saab minult ülesanded. Õpilane tohib kasutada kirjutusvahendit, taskukalkulaatorit ja enda aru. Soorituskohta muuta, seega ka sooritusruumist väljas käia, ega omavahel suhelda sooritamise kestel, välja arvatud minuga, ei tohi. Spikri valmistamine kontrolltööks on lubatud, kuid selle kasutamine keelatud. Mis tahes kontrolltöö reegliga vastuoluliselt esmakordselt käitudes saab õpilane hoiatuse, teisel kuni neljandal korral väheneb maksimaalne võimalik trimestri hinne, viiendal korral selles päevas enam õpilase sooritust ei arvestata ning ta asub harjutama, et järgmine kord vastavalt reeglitele kontrolltöö sooritada. Kontrolltööd mittesooritavad õpilased ei tohi suhelda üldse. Kontrolltööle on lubatud õpilane, kellel on vastavas kursuses vähemalt üks õpiväljund saavutatud. Vastasel juhul on trimestri hinne 1 või 2. Kontrolltöös on ülesanded teemadekaupa läbisegi, ent iga teema osas suureneva keerukuse järjekorras. Iga õpiväljundi osas jääb kehtima kontrolltöös saavutatud tulemuse hinne, mis tühistab eelnevalt lühitestiga saavutatu hinde.

Iga õpiväljund on määratud tasemega Bloomi taksonoomia järgi ning kõik hinded kaalutakse selle tasemega.

Kuna oluline osa õppimist toimub harjutuslehtede abil, mille järgimine ja alleshoidmine on abiks edasises õppimises, siis, kui sul on alles kõik talle antud harjutuslehed ja sa näitad need ette kokkuvõtvaks hindamiseks, on su kokkuvõtlik hinne ühe võrra suurem.
