# Lähtetest

<!-- ## Ülesanded -->

```{r label="tasks", echo=FALSE, results='asis'}
librarian::shelf(c(
  "profvis"
))
# profvis({
goals <- list(
  list( # 1
    goal = "teab andmete liike ja andmete kogumise erinevaid meetodeid (mõõtmine, küsimustik)",
    level = 1
  ),
  list( # 2
    goal = "iseloomustab andmestikku aritmeetilise keskmise, mediaani, moodi, miinimumi, maksimumi ja ulatuse järgi",
    level = 4
  ),
  list( # 3
    goal = "loeb, mõistab ja selgitab andmeid tabelist, tulp-, sektor-, joon- ja punktdiagrammilt",
    level = 4
  ),
  list( # 4
    goal = "selgitab protsendi, promilli ja protsendipunkti mõiste tähendust",
    level = 2
  ),
  list( # 5
    goal = "teisendab protsendi kümnendmurruks ja harilikuks murruks ning vastupidi",
    level = 3
  ),
  list( # 6
    goal = "selgitab tõenäosuse tähendust, arvutab elulistel juhtudel sündmuse tõenäosuse (sh mündivise, täringu veeretamine, kaardimäng, loosimine)",
    level = 3
  ),
  list( # 7
    goal = "kasutab (igapäevaelu) ülesannete lahendamisel otstarbekat osamäära esitusviisi (protsent, harilik murd, kümnendmurd)",
    level = 3
  ),
  list( # 8
    goal = "kasutab protsentarvutusel erinevaid lahendusmeetodeid (ühikumeetod, võrre, skeem,
algoritm)",
    level = 3
  ),
  list( # 9
    goal = "lahendab protsentarvutuse tüüpülesandeid (osa leidmine, terviku leidmine, osamäära
leidmine, suuruse muutumine)",
    level = 3
  ),
  list( # 10
    goal = "moodustab reaalsetest andmetest sageduste ja suhteliste sageduste tabeli",
    level = 3
  ),
  list( # 11
    goal = "väljendab protsentides esitatud informatsiooni visuaalselt (graafikud, diagrammid) ja vastupidi",
    level = 3
  ),
  list( # 12
    goal = "kasutab protsentarvutust otsuse tegemiseks ja põhjendamiseks (nt laen, hoius, intress, maksud, investeerimine)",
    level = 3
  ),
  list( # 13
    goal = "ümardab ratsionaalarve etteantud järguni",
    level = 3
  ),
  list( # 14
    goal = "selgitab naturaalarvulise astendajaga astendamise tähendust (E)",
    level = 2
  ),
  list( # 15
    goal = "selgitab arvu ruutjuure tähendust",
    level = 2
  ),
  list( # 16
    goal = "leiab peast või taskuarvutil ruutjuure",
    level = 3
  ),
  list( # 17
    goal = "põhjendab ja kasutab astendamisreegleid",
    level = 4
  ),
  list( # 18
    goal = "liidab, lahutab, korrutab, jagab ja astendab naturaalarvulise astendajaga ratsionaalarve peast,
kirjalikult ja taskuarvutiga ning rakendab tehete järjekorda",
    level = 4
  ),
  list( # 19
    goal = "lihtsustab kuni kolmetehtelisi täisavaldisi",
    level = 3
  ),
  list( # 20
    goal = "korrastab üks- ja hulkliikmeid, liidab, lahutab ning korrutab üks- ja hulkliikmeid ning jagab
üksliikmeid ja hulkliiget üksliikmega",
    level = 3
  ),
  list( # 21
    goal = "üldistab harilike murdude arvutusreeglid algebralistele murdudele",
    level = 5
  ),
  list( # 22
    goal = "lihtsustab kahetehtelisi ratsionaalavaldisi",
    level = 3
  ),
  list( # 23
    goal = "tegurdab hulkliikmeid (toob teguri sulgude ette, kasutab ja põhjendab ruutude vahe, summa
ruudu ja vahe ruudu abivalemeid, tegurdab ruutkolmliiget)",
    level = 4
  ),
  list( # 24
    goal = "taandab ja laiendab algebralist murdu ning liidab, lahutab, korrutab ja jagab kaht algebralist
murdu",
    level = 3
  ),
  list( # 25
    goal = "teab põik- ja lähisnurkade mõisteid ja nende nurkade seoseid paralleelsete sirgete korral",
    level = 1
  ),
  list( # 26
    goal = "põhjendab ja kasutab sirgete paralleelsuse tunnuseid",
    level = 4
  ),
  list( # 27
    goal = "kirjeldab kujundite omadusi ning klassifitseerib kujundeid ühiste omaduste põhjal",
    level = 2
  ),
  list( # 28
    goal = "joonestab ja konstrueerib (käsitsi ja arvutiga) tasandilisi kujundeid (korrapärane hulknurk, kolmnurk, rööpkülik, trapets, ring) etteantud elementide järgi korrapärase hulknurga ja kolmnurga sise-ja ümberringjoone",
    level = 3
  ),
  list( # 29
    goal = "teab kesk- ja piirdenurga mõisteid ning nendevahelist seost",
    level = 1
  ),
  list( # 30
    goal = "teab ringjoone puutuja mõistet ja omadust",
    level = 1
  ),
  list( # 31
    goal = "visandab ruumilisi kujundeid (püstprisma, püramiid, silinder, koonus, kera)",
    level = 3
  ),
  list( # 32
    goal = "selgitab ja rakendab Pythagorase teoreemi",
    level = 3
  ),
  list( # 33
    goal = "leiab täisnurkse kolmnurga joonelemendid (sh kasutades trigonomeetrilisi seoseid)",
    level = 3
  ),
  list( # 34
    goal = "nimetab võrrandi põhiomadusi",
    level = 1
  ),
  list( # 35
    goal = "mõistab ja tunneb ära võrdelise ja pöördvõrdelise seose (nt liikumisel teepikkus, aeg, kiirus) (E)",
    level = 2
  ),
  list( # 36
    goal = "selgitab eluliste näidete põhjal võrdelise, lineaarse ja pöördvõrdelise sõltuvuse tähendust",
    level = 2
  ),
  list( # 37
    goal = "lahendab lineaar- ja võrdekujulisi võrrandeid ning lineaarvõrrandisüsteeme kasutades
võrrandi põhiomadusi (sh graafiliselt ning arvutiprogrammide abil)",
    level = 3
  ),
  list( # 38
    goal = "lahendab täielikke ja mittetäielikke ruutvõrrandeid",
    level = 3
  ),
  list( # 39
    goal = "koostab ja lahendab tekstülesandeid, mis lahenduvad võrrandi või võrrandisüsteemi abil (sh
võrdelise jaotamise ülesandeid)",
    level = 6
  ),
  list( # 40
    goal = "selgitab ruutfunktsiooni nullkohtade ja haripunkti tähendust ja omavahelist seost, leiab need valemist ning jooniselt",
    level = 3
  ),
  list( # 41
    goal = "joonestab etteantud funktsiooni graafiku (sirge, hüperbooli, parabooli) (nii käsitsi kui ka arvutiprogrammiga) ning loeb graafikult funktsiooni ja argumendi väärtusi",
    level = 3
  ),
  list( # 42
    goal = "selgitab arvutiga tehtud dünaamilisi jooniseid kasutades funktsiooni graafiku asendi ja kuju sõltuvust funktsiooni avaldises olevatest kordajatest (ruutfunktsiooni korral ainult ruutliikme kordajast ja vabaliikmest)",
    level = 4
  ),
  list( # 43
    goal = "lahendab geomeetrilise sisuga probleemülesandeid (sh kasutades korrapärase hulknurga omadusi, Thalese teoreemi)",
    level = 3
  ),
  list( # 44
    goal = "kasutab probleemülesannete lahendamiseks hulknurkade sarnasust (nt maa-alade plaanistamine)",
    level = 4
  ),
  list( # 45
    goal = "arvutab tasandiliste kujundite (korrapärane hulknurk, kolmnurk, rööpkülik, romb, trapets, ring) joonelemendid, ümbermõõdu, pindala",
    level = 3
  ),
  list( # 46
    goal = "arvutab ruumiliste kujundite (püstprisma, püramiid, silinder, koonus, kera) joonelemendid, pindala ja ruumala",
    level = 3
  ),
  list( # 47
    goal = "selgitab oma algebra- ja geomeetriateadmiste elulisi rakendusvõimalusi",
    level = 2
  ),
  list( # 48
    goal = "teab kolmnurga ja trapetsi kesklõigu mõistet ning nende omadusi",
    level = 1
  ),
  list( # 49
    goal = "arvutab arvu 10 negatiivse täisarvulise astendajaga astme väärtuse",
    level = 4
  ),
  list( # 50
    goal = "kirjutab suuri ja väikseid arve standardkujul",
    level = 4
  ),
  list( # 51
    goal = "eristab hüpoteesi, eeldust, väidet ja tõestust, selgitab mõne teoreemi tõestuskäiku, vajaduse korral tuletab lihtsamaid valemeid",
    level = 4
  )
)

tasks <- list(
  list(goal = 1, level = 1, task = "Millised on andmete liigid?"),
  list(goal = 1, level = 1, task = "Nimeta üks andmete kogumise meetod!"),
  list(goal = 1, level = 1, task = "Vaata allolevaid väiteid ja märgi, millised nendest on kvalitatiivsed andmed:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] Temperatuur.
    \\item[\\Square] Aeg.
    \\item[\\Square] Laste arv peres.
    \\item[\\Square] Visatud täringu tulemus.
    \\item[\\Square] Hinnang \"meeldib/ ei meeldi\".
    \\item[\\Square] Automark.
    \\item[\\Square] Elukoht.
    \\item[\\Square] Õpilaste arv klassis.
    \\item[\\Square] Pikkus.
    \\item[\\Square] Mass.
    \\item[\\Square] Silmavärv.
  \\end{itemize}"),
  list(goal = 1, level = 1, task = "Vaata allolevaid väiteid ja märgi, millised nendest on kvantitatiivsed andmed:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] Temperatuur.
    \\item[\\Square] Aeg.
    \\item[\\Square] Laste arv peres.
    \\item[\\Square] Visatud täringu tulemus.
    \\item[\\Square] Hinnang \"meeldib/ ei meeldi\".
    \\item[\\Square] Automark.
    \\item[\\Square] Elukoht.
    \\item[\\Square] Õpilaste arv klassis.
    \\item[\\Square] Pikkus.
    \\item[\\Square] Mass.
    \\item[\\Square] Silmavärv.
  \\end{itemize}"),
  list(goal = 1, level = 1, task = "Vaata allolevaid väiteid ja märgi, millised nendest on diskreetsed andmed:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] Temperatuur.
    \\item[\\Square] Aeg.
    \\item[\\Square] Laste arv peres.
    \\item[\\Square] Visatud täringu tulemus.
    \\item[\\Square] Õpilaste arv klassis.
    \\item[\\Square] Pikkus.
    \\item[\\Square] Mass.
  \\end{itemize}"),
  list(goal = 1, level = 1, task = "Vaata allolevaid väiteid ja märgi, millised nendest on jätkuvad andmed:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] Temperatuur.
    \\item[\\Square] Aeg.
    \\item[\\Square] Laste arv peres.
    \\item[\\Square] Visatud täringu tulemus.
    \\item[\\Square] Õpilaste arv klassis.
    \\item[\\Square] Pikkus.
    \\item[\\Square] Mass.
  \\end{itemize}"),
  list(goal = 2, level = 1, task = "Mis on aritmeetiline keskmine?"),
  list(goal = 2, level = 1, task = "Mis on mediaan?"),
  list(goal = 2, level = 1, task = "Mis on mood?"),
  list(goal = 2, level = 1, task = "Mis on miinimum?"),
  list(goal = 2, level = 1, task = "Mis on maksimum?"),
  list(goal = 2, level = 1, task = "Mis on ulatus?"),
  list(goal = 2, level = 2, task = "Esita näide aritmeetilise keskmise kohta!"),
  list(goal = 2, level = 2, task = "Esita näide mediaani kohta!"),
  list(goal = 2, level = 2, task = "Esita näide moe kohta!"),
  list(goal = 2, level = 2, task = "Esita näide miinimumi kohta!"),
  list(goal = 2, level = 2, task = "Esita näide maksimumi kohta!"),
  list(goal = 2, level = 2, task = "Esita näide ulatuse kohta!"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite aritmeetiline keskmine?"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite mood?"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite mediaan?"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite miinimum?"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite maksimum?"),
  list(goal = 2, level = 3, task = "Õpetaja telefoniaadress on 56204556. Milline on nende numbrite ulatus?"),
  list(goal = 2, level = 4, task = "Kahe rühma kontrolltöö punktisummad olid:\\leavevmode\\
- rühm A: 6, 7, 7, 8, 9,\\leavevmode\\
- rühm B: 3, 5, 7, 9, 11.\\leavevmode\\
Võrdle tulemusi ja analüüsi: kumb rühm oli ühtlasema tasemega?"),
  list(goal = 2, level = 4, task = "Kahe rühma kontrolltöö punktisummad olid:\\leavevmode\\
- rühm A: 6, 7, 7, 8, 9,\\leavevmode\\
- rühm B: 3, 5, 7, 9, 11.\\leavevmode\\
Võrdle tulemusi ja analüüsi: kumb rühm oli keskmiselt tugevam?"),
  list(goal = 3, level = 1, task = "Mis on tulpdiagramm?"),
  list(goal = 3, level = 1, task = "Mis on sektordiagramm?"),
  list(goal = 3, level = 1, task = "Mis on joondiagramm?"),
  list(goal = 3, level = 1, task = "Mis on punktdiagramm?"),
  list(goal = 3, level = 3, task = "Roosioksa talu pererahval on põllumaad \\qty{10}{\\hectare}, karjamaad \\qty{6}{\\hectare}, metsamaad \\qty{22}{\\hectare} ja elamumaad \\qty{2}{\\hectare}. Vaata sektordiagrammi joonist \\@ref(fig:tasks-sector-diagram) ja märgi, kui palju on metsamaad:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{80}{\\percent}$.
    \\item[\\Square] $\\qty{55}{\\percent}$.
    \\item[\\Square] $\\qty{47}{\\percent}$.
    \\item[\\Square] $\\qty{22}{\\percent}$.
  \\end{itemize}"),
  list(goal = 3, level = 3, task = "Roosioksa talu pererahval on põllumaad \\qty{10}{\\hectare}, karjamaad \\qty{6}{\\hectare}, metsamaad \\qty{22}{\\hectare} ja elamumaad \\qty{2}{\\hectare}. Vaata sektordiagrammi joonist \\@ref(fig:tasks-sector-diagram) ja märgi, kui palju on karjamaad:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{34}{\\percent}$.
    \\item[\\Square] $\\qty{15}{\\percent}$.
    \\item[\\Square] $\\qty{17}{\\percent}$.
    \\item[\\Square] $\\qty{6}{\\percent}$.
  \\end{itemize}"),
  list(goal = 3, level = 3, task = "Roosioksa talu pererahval on põllumaad \\qty{10}{\\hectare}, karjamaad \\qty{6}{\\hectare}, metsamaad \\qty{22}{\\hectare} ja elamumaad \\qty{2}{\\hectare}. Vaata sektordiagrammi joonist \\@ref(fig:tasks-sector-diagram) ja märgi, kui palju on elamumaad:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{9}{\\percent}$.
    \\item[\\Square] $\\qty{5}{\\percent}$.
    \\item[\\Square] $\\qty{2}{\\percent}$.
  \\end{itemize}"),
  list(goal = 3, level = 3, task = "Roosioksa talu pererahval on põllumaad \\qty{10}{\\hectare}, karjamaad \\qty{6}{\\hectare}, metsamaad \\qty{22}{\\hectare} ja elamumaad \\qty{2}{\\hectare}. Vaata sektordiagrammi joonist \\@ref(fig:tasks-sector-diagram) ja märgi, kui palju on põllumaad:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{25}{\\percent}$.
    \\item[\\Square] $\\qty{10}{\\percent}$.
  \\end{itemize}"),
  list(goal = 3, level = 4, task = "Roosioksa talu pererahval on põllumaad \\qty{10}{\\hectare}, karjamaad \\qty{6}{\\hectare}, metsamaad \\qty{22}{\\hectare} ja elamumaad \\qty{2}{\\hectare}. Kirjuta sektordiagrammile joonisel \\@ref(fig:tasks-sector-diagram) erinevate maatükkide suurused protsentides!"),
  list(
    goal = 5,
    level = 3,
    task = "Märgi kõik arvud, millega on võrdne \\num{0,4}:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{40}{\\percent}$.
    \\item[\\Square] $\\frac{1}{25}$.
    \\item[\\Square] $\\frac{2}{5}$.
    \\item[\\Square] $\\frac{4}{10}$.
    \\item[\\Square] $\\frac{1}{5}$.
    \\item[\\Square] $\\frac{1}{6}$.
  \\end{itemize}"),
  list(
    goal = 5,
    level = 3,
    task = "Märgi kõik arvud, millega on võrdne \\num{0,75}:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{75}{\\percent}$.
    \\item[\\Square] $\\frac{3}{4}$.
    \\item[\\Square] $\\frac{1}{3}$.
    \\item[\\Square] $\\frac{1}{8}$.
    \\item[\\Square] $\\qty{55}{\\percent}$.
  \\end{itemize}"
  ),
  list(
    goal = 5,
    level = 3,
    task = "Märgi kõik arvud, millega on võrdne $\\frac{1}{2}$:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\num{0,5}$.
    \\item[\\Square] $\\qty{15}{\\percent}$.
    \\item[\\Square] $\\qty{50}{\\percent}$.
  \\end{itemize}"
  ),
  list(
    goal=5,
    level=3,
    task="Täida tabel \\@ref(tab:tasks-tables-fractions)."
  ),
  list(goal = 8, level = 3, task = "Et leida \\qty{10}{\\percent} arvust, jagan arvu:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\num{10}$'ga.
    \\item[\\Square] $\\num{5}$'ga.
  \\end{itemize}"),
  list(goal = 8, level = 3, task = "Et leida veerand arvust, jagan arvu:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\num{25}$'ga.
    \\item[\\Square] $\\num{50}$'ga.
    \\item[\\Square] $\\num{15}$'ga.
    \\item[\\Square] $\\num{4}$'ga.
  \\end{itemize}"),
  list(goal = 8, level = 3, task = "Et leida \\qty{3}{\\percent} arvust, korrutan arvu:\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\num{33}$'ga.
    \\item[\\Square] $\\num{1,5}$'ga.
    \\item[\\Square] $\\num{3,3333}$'ga.
    \\item[\\Square] $\\num{0,03}$'ga.
  \\end{itemize}"),
  list(goal = 9, level = 3, task = "Mari ostis \\num{3} eurot maksva jäätise, ta kasutas selleks \\qty{15}{\\percent} oma taskuvaluutat. Kui palju oli Maril taskuvaluutat?\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\qty{0,21}{\\euro}$.
    \\item[\\Square] $\\num{2,5}{\\euro}$.
    \\item[\\Square] $\\num{2,55}{\\euro}$.
    \\item[\\Square] $\\num{20}{\\euro}$.
    \\item[\\Square] $\\num{245}{\\euro}$.
  \\end{itemize}"),
  list(goal = 9, level = 3, task = "Sügisel maksis \\qty{1}{\\kilo\\g} kartuleid \\num{30} senti ja kevadel \\num{40} senti. Mitme protsendi võrra tõusis kartuli \\qty{1}{\\kg} hind?\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $\\num{10}$.
    \\item[\\Square] $\\num{33}\\frac{1}{3}$.
  \\end{itemize}"),
  list(goal = 12, level = 5, task = "Raamatu *Eesti reisijuht* hind enne allahindlust oli $\\qty{20}{\\euro}$. Kauba hinna muutus on esitatud pildil \\@ref(fig:tasks-discount-book). Marial oli \\num{10} eurot. Kas Maria saab selle raamatu osta?\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] Maria saab osta, sest \\qty{59}{\\percent} kahekümnest eurost on vähem kui $\\num{10}$ eurot.
    \\item[\\Square] Maria ei saa osta, sest \\qty{41}{\\percent} kahekümnest eurost on rohkem kui $\\num{10}$ eurot.
    \\item[\\Square] Maria saab osta, sest \\qty{41}{\\percent} kahekümnest eurost on vähem kui $\\num{10}$ eurot.
    \\item[\\Square] Maria ei saa osta, sest \\qty{59}{\\percent} kahekümnest eurost on rohkem kui $\\num{10}$ eurot.
  \\end{itemize}"),
  list(
    goal=14,
    level=2,
    task="Mida tähendab $4^2$?"
  ),
  list(
    goal = 17,
    level = 4,
    task = "Milline väide on tõene?
  \\begin{itemize}
    \\item[\\Square] $x^2 \\cdot x^3 = x^6$.
    \\item[\\Square] $x^2 \\cdot x^4 = x^6$.
  \\end{itemize}"),
  list(
    goal = 17,
    level = 4,
    task = "Milline väide on tõene?
  \\begin{itemize}
    \\item[\\Square] $b^{10}:b^5=b^2$.
    \\item[\\Square] $b^{10}:b^8=b^2$.
  \\end{itemize}"),
  list(
    goal = 17,
    level = 4,
    task = "$(5^{\\blank{2}})^4 = 5^8.$"),
  list(
    goal = 18,
    level = 4,
    task = "$-(-4)^0=$
    \\begin{itemize}
      \\item{\\Circle} 4.
      \\item{\\Circle} -4.
      \\item{\\Circle} -1.
      \\item{\\Circle} 1.
    \\end{itemize}"
  ),
  list(
    goal=18,
    level=4,
    task="$$1\\frac{2}{3}\\cdot(-0,3)=$$
    \\begin{itemize}
      \\item[\\Square] $\\frac{1}{7}$.
      \\item[\\Square] $-\\frac{1}{2}$.
    \\end{itemize}
    "
  ),
  list(
    goal = 20,
    level = 3,
    task = "Vali alljärgnevatest avaldistest üksliikme $4x^2 \\cdot (-xy) \\cdot (-y)$ normaalkuju:
    \\begin{itemize}
      \\item[\\Circle] $4x^3y^2.$
      \\item[\\Circle] $4x^2y^2.$
      \\item[\\Circle] $-4x^3y^2.$
      \\item[\\Circle] $-4x^2y^2.$
    \\end{itemize}"
  ),
  list(
    goal = 20,
    level = 3,
    task = "$2(a-b)-(3a+b)=$
    \\begin{itemize}
      \\item[Square] $1a-1b.$
      \\item[Square] $-1a-3b.$
    \\end{itemize}"
  ),
  list(
    goal=20,
    level=3,
    task="Avaldist $2x+3y-3x-5y$ nimetatakse
    \\begin{itemize}
      \\item[\\Square] $-x-2y$.
      \\item[\\Square] hulkliikmeks.
      \\item[\\Square] võrduseks.
      \\item[\\Square] võrrandiks.
      \\item[\\Square] üksliikmeks.
    \\end{itemize}
    $2x+3y-3x-5y=\\blank{-}x-2{y}.$"
  ),
  list(
    goal=20,
    level=3,
    task="$$\\begin{cases}
x = -1 \\\\
y = -2
\\end{cases} \\rightarrow 2x^2 y+3xy+5y=$$
    \\begin{itemize}
      \\item[\\Square] -8.
      \\item[\\Square] 2.
    \\end{itemize}"
  ),
  list(goal = 22, level = 3, task = "$-6 + 13+6-20-7=$\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] \\num{-14}.
    \\item[\\Square] \\num{-13}.
    \\item[\\Square] \\num{-2}.
    \\item[\\Square] \\num{2}.
  \\end{itemize}"),
  list(goal = 22, level = 3, task = "$\\frac{1}{3}-0,5=$\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] $-\\frac{1}{6}$.
    \\item[\\Square] \\num{-0,2}.
    \\item[\\Square] \\num{0,2}.
    \\item[\\Square] $\\frac{1}{6}$.
  \\end{itemize}"),
  list(
    goal=23,
    level=4,
    task="$m^2-n^2=$
    \\begin{itemize}
      \\item[\\Circle] $n^2-m^2$.
      \\item[\\Circle] $(m-n)(n^2+mn+m^2)$.
      \\item[\\Circle] $(m+n)(m-n)$.
      \\item[\\Circle] $m^2+2mn+n^2$.
      \\item[\\Circle] $m^2+mn+n^2$.
      \\item[\\Circle] $m^2+n^2-2mn$.
    \\end{itemize}"
  ),
  list(
    goal=23,
    level=4,
    task="$(n-m)(m+n)=$
    \\begin{itemize}
      \\item[\\Circle] $n^2-m^2$.
      \\item[\\Circle] $(m-n)(n^2+mn+m^2)$.
      \\item[\\Circle] $(m+n)(m-n)$.
      \\item[\\Circle] $m^2+2mn+n^2$.
      \\item[\\Circle] $m^2+mn+n^2$.
      \\item[\\Circle] $m^2+n^2-2mn$.
    \\end{itemize}"
  ),
  list(
    goal=23,
    level=4,
    task="$(m-n)^2=$
    \\begin{itemize}
      \\item[\\Circle] $n^2-m^2$.
      \\item[\\Circle] $(m-n)(n^2+mn+m^2)$.
      \\item[\\Circle] $(m+n)(m-n)$.
      \\item[\\Circle] $(m-n)(m-n)$.
      \\item[\\Circle] $m^2+2mn+n^2$.
      \\item[\\Circle] $m^2+mn+n^2$.
      \\item[\\Circle] $m^2+n^2-2mn$.
    \\end{itemize}"
  ),
  list(
    goal=23,
    level=4,
    task="$(m+n)(m+n)=$
    \\begin{itemize}
      \\item[\\Circle] $n^2-m^2$.
      \\item[\\Circle] $(m-n)(n^2+mn+m^2)$.
      \\item[\\Circle] $(m+n)(m-n)$.
      \\item[\\Circle] $m^2+2mn+n^2$.
      \\item[\\Circle] $m^2+mn+n^2$.
      \\item[\\Circle] $m^2+n^2-2mn$.
    \\end{itemize}"
  ),
  list(
    goal=23,
    level=4,
    task="$$3x^2($$
    \\begin{itemize}
      \\item[\\Square] 12
      \\item[\\Square] -12
    \\end{itemize}
    $$xy-4y+5)=-36x^3y-$$
    \\begin{itemize}
      \\item[\\Square] 15
      \\item[\\Square] (-144)
      \\item[\\Square] 12
    \\end{itemize}
    $$x^2y+15x^2.$$"
  ),
  list(
    goal=23,
    level=4,
    task="$$18x^2y+2y=\\blank{2}y(9x^2+\\blank{1}).$$"
  ),
  list(
    goal=23,
    level=4,
    task="$$(x-3y)^2=x^2\\blank{-6}xy+9y^2.$$"
  ),
  list(
    goal=23,
    level=4,
    task="$$(7+m)(m-7)=m^2\\blank{-49}.$$"
  ),
  list(
    goal=23,
    level=4,
    task="Joonisel \\@ref(fig:tasks-figures-area-of-shape) esitatud kujundi pindala lihtsustatud avaldis on
    $$S=\\blank{(m+3)^2}$$
    $$\\blank{-(m+2)(m-3)}$$
    $$\\blank{=7m+15}.$$
    Arvuta kujundi pindala, kui  $m=\\frac{2}{7}\\, \\unit{\\centi\\m}$.
    Kujundi pindala on $S=\\blank{17}\\unit{\\square\\centi\\m}$."
  ),
  list(goal = 25, level = 1, task = "Joonisel \\@ref(fig:tasks-lines-angles) on näidatud kahe sirge lõikamisel kolmanda sirgega tekkinud nurgad.\\leavevmode\\
    Nurgad \\qty{113}{\\degree} ja $\\alpha$ on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] lähisnurgad.
      \\item[\\Square] põiknurgad.
      \\item[\\Square] kõrvunurgad.
      \\item[\\Square] tippnurgad.
      \\item[\\Square] sirgnurgad.
      \\item[\\Square] \\qty{113}{\\degree}.
    \\end{itemize}
    Nurk $\\alpha=$\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] \\qty{84}{\\degree}.
      \\item[\\Square] \\qty{113}{\\degree}.
      \\item[\\Square] \\qty{163}{\\degree}.
      \\item[\\Square] \\qty{67}{\\degree}.
    \\end{itemize}
    Nurgad \\qty{113}{\\degree} ja $\\beta$ on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] lähisnurgad.
      \\item[\\Square] põiknurgad.
      \\item[\\Square] kõrvunurgad.
      \\item[\\Square] tippnurgad.
      \\item[\\Square] vastasnurgad.
      \\item[\\Square] \\qty{67}{\\degree}.
    \\end{itemize}
    Nurk $\\beta=$\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] \\qty{96}{\\degree}.
      \\item[\\Square] \\qty{67}{\\degree}.
      \\item[\\Square] \\qty{113}{\\degree}.
      \\item[\\Square] \\qty{84}{\\degree}.
    \\end{itemize}
  "),
  list(goal = 26, level = 4, task = "Kui kaks sirget $s$ ja $t$ on paralleelsed, siis\\leavevmode\\
  \\begin{itemize}
    \\item[\\Square] nende lõikamisel kolmanda sirgega $u$ tekivad võrdsed tippnurgad.
    \\item[\\Square] nende lõikamisel kolmanda sirgega $u$ tekivad võrdsed põiknurgad.
  \\end{itemize}
  Vastav joonis on
  \\begin{itemize}
    \\item[\\Square] @ref(fig:tasks-lines-top-angles).
    \\item[\\Square] @ref(fig:tasks-lines-close-angles).
    \\item[\\Square] @ref(fig:tasks-lines-skewed-angles).
    \\item[\\Square] @ref(fig:tasks-lines-side-angles).
  \\end{itemize}"),
  list(goal = 26, level = 4, task = "
  \\begin{itemize}
    \\item[\\Square] Kui kahe sirge $s$ ja $t$ lõikamisel kolmanda sirgega $u$ tekkivate kõrvunurkade summa on \\qty{180}{\\degree},
    \\item[\\Square] Kui kahe sirge $s$ ja $t$ lõikamisel kolmanda sirgega $u$ tekkivate lähisnurkade summa on \\qty{180}{\\degree},
  \\end{itemize}
  siis on kaks sirget $s$ ja $t$ paralleelsed ja vastav joonis on
  \\begin{itemize}
    \\item[\\Square] @ref(fig:tasks-lines-top-angles).
    \\item[\\Square] @ref(fig:tasks-lines-close-angles).
    \\item[\\Square] @ref(fig:tasks-lines-skewed-angles).
    \\item[\\Square] @ref(fig:tasks-lines-side-angles).
  \\end{itemize}"),
  list(
    goal=28,
    level=3,
    task="Märgi joonisele \\@ref(fig:tasks-figures-triangles-circles), kus on kolmnurga küljepoolitajad, nurgapoolitajad, külgede keskristsirged, punkt $C$ siseringjoone keskpunktina, ümberringjoone keskpunktina, mediaanide lõikepunktina!"
  ),
  list(
    goal=29,
    level=1,
    task="Joonisel \\@ref(fig:tasks-figures-circle-central-border-angle) on ringjoon keskpunktiga $O$.\\leavevmode\\
    $\\angle CAB$ on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Circle] kesk-
      \\item[\\Circle] piirde-
      \\item[\\Circle] täis-
      \\item[\\Circle] sirg-
    \\end{itemize}
    nurk.\\leavevmode\\
    Kui $\\angle CAB=\\ang{30}$, siis $\\angle COB=\\blank{\\ang{60}}$."
  ),
  list(
    goal=29,
    level=1,
    task="Joonisel \\@ref(fig:tasks-figures-circle-central-2-border-angle) on ringjoon, mille keskpunkt asetseb punktis $C$.\\leavevmode\\
    Arvuta nurkade $KNL$ ja $KML$ suurus, kui $\\angle KCL=\\ang{28}$.\\leavevmode\\
    $\\angle KNL=\\blank{\\ang{14}}, \\angle KML=\\blank{\\ang{14}}$."
  ),
  list(
    goal=30,
    level=1,
    task="Joonisel \\@ref(fig:tasks-figures-circle-tangent) on ringjoonele keskpunktiga $C$ joonestatud kaks puutujat $LK$ ja $LM$. Märgista iga õige väide!\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] Joonisel on lõigud $KL$ ja $LM$ erineva pikkusega.
      \\item[\\Square] Kolmnurgad $KLC$ ja $LMC$ on täisnurksed.
      \\item[\\Square] Nelinurga $KLMC$ sisenurkade summa on \\ang{360}.
      \\item[\\Square] Kui $\\angle MCK=\\ang{130}$, siis $\\angle KLM=\\ang{65}$.
    \\end{itemize}"
  ),
  list(
    goal = 34,
    level = 1,
    task = "Vali võrrandiga $x-5=9$ samaväärne võrrand:
  \\begin{itemize}
    \\item[\\Circle] $2x-10=19$.
    \\item[\\Circle] $x+5=14$.
    \\item[\\Circle] $x=-9+5$.
    \\item[\\Circle] $x=5+9$.
  \\end{itemize}"),
  list(
    goal = 34,
    level = 1,
    task = "Vai võrrandiga $\\frac{2}{x} = \\frac{7}{3}$ samaväärne võrrand:
  \\begin{itemize}
    \\item[\\Circle] $\\frac{3}{x} = \\frac{2}{7}$.
    \\item[\\Circle] $\\frac{x}{3} = \\frac{7}{2}$.
    \\item[\\Circle] $2x=7 \\cdot 3$.
    \\item[\\Circle] $2 \\cdot 3=7x$.
  \\end{itemize}"),
  list(
    goal = 37,
    level = 3,
    task = "On antud võrrand $5x+7=x-1$. Milline arv on selle võrrandi lahendiks?
  \\begin{itemize}
    \\item[\\Circle] \\num{2}.
    \\item[\\Circle] \\num{-2}.
    \\item[\\Circle] \\num{-3}.
    \\item[\\Circle] \\num{-1}.
  \\end{itemize}"),
  list(
    goal = 37,
    level = 3,
    task = "Täida lünk nii, et võrrandi lahend oleks $x=1$:\\leavevmode\\
    $2x+4=\\blank{7}-x$."
  ),
  list(
    goal = 37,
    level = 3,
    task = "$x=1 \\rightarrow 2x+4=$
    \\begin{itemize}
      \\item[\\Square] 16
      \\item[\\Square] 7
      \\item[\\Square] 6
    \\end{itemize}
    $$-x.$$"
  ),
  list(
    goal = 37,
    level = 3,
    task = "Võrrandi $\\frac{5x-2}{5}=x+1$ lahendamisel korrutatakse võrrandi mõlemat poolt arvuga 5:
    $$\\frac{5x-2}{5}=x+1|\\cdot 5.$$
    Millise võrrandi saad? Kirjuta lünkadesse sobivad arvud:
    $$\\blank{5}x-\\blank{2}=\\blank{5}x+5$$.
    Milline allpool olevatest lausetest esitab saadud võrrandi lahendit?
  \\begin{itemize}
    \\item[\\Circle] Võrrandil lahendid puuduvad.
    \\item[\\Circle] Võrrandi lahend on $x=0$.
    \\item[\\Circle] Võrrandi lahend on $x=7$.
    \\item[\\Circle] Võrrandil on lõpmata palju lahendeid..
  \\end{itemize}"),
  list(
    goal = 37,
    level = 3,
    task = "Lahenda võrrand $0,5x+4=5$! Võrrandi lahend on
  \\begin{itemize}
    \\item[\\Square] $2$.
    \\item[\\Square] $2x$.
  \\end{itemize}"),
  list(
    goal = 37,
    level = 3,
    task = "Lahenda võrrand $7-3y=10$! Võrrandi lahend on
  \\begin{itemize}
    \\item[\\Square] $1y$.
    \\item[\\Square] $1x$.
    \\item[\\Square] $-1$.
  \\end{itemize}"),
  list(
    goal=37,
    level=3,
    task="On antud kahe tundmatuga lineaarvõrrand $3x-4y=2$. Milline arvupaar sobib võrrandi lahendiks?
    \\begin{itemize}
      \\item[\\Circle] $\\begin{cases}
        x=2\\\\
        y=1
      \\end{cases}.$
    \\end{itemize}
    \\begin{itemize}
      \\item[\\Circle] $\\begin{cases}
        x=0\\\\
        y=6
      \\end{cases}.$
    \\end{itemize}
    \\begin{itemize}
      \\item[\\Circle] $\\begin{cases}
        x=4\\\\
        y=3
      \\end{cases}.$
    \\end{itemize}
    \\begin{itemize}
      \\item[\\Circle] $\\begin{cases}
        x=-2\\\\
        y=2
      \\end{cases}.$
    \\end{itemize}
    "
  ),
  list(
    goal=37,
    level=3,
    task="On antud kahe tundmatuga lineaarvõrrandidüsteem:
    $\\begin{cases}
      2x+y=5\\\\
      3x-2y=4
    \\end{cases}$. Milline arvupaar sobib süsteemi lahendiks?
    \\begin{itemize}
      \\item[\\Circle] $\\begin{cases}
        x=-2\\\\
        y=1
      \\end{cases}.$
      \\item[\\Circle] $\\begin{cases}
        x=0\\\\
        y=-2
      \\end{cases}.$
      \\item[\\Circle] $\\begin{cases}
        x=0\\\\
        y=5
      \\end{cases}.$
      \\item[\\Circle] $\\begin{cases}
        x=2\\\\
        y=1
      \\end{cases}.$
    \\end{itemize}
    "
  ),
  list(
    goal=37,
    level=3,
    task="
    $\\begin{cases}
      3x-4y=15\\\\
      2x-4y=-10
    \\end{cases} \\rightarrow$
    \\begin{itemize}
      \\item[\\Square] $\\begin{cases}
        x=1\\\\
        y=-3
      \\end{cases}.$
      \\item[\\Square] $\\begin{cases}
        x=-1\\\\
        y=0
      \\end{cases}.$
    \\end{itemize}
    "
  ),
  list(
    goal=37,
    level=3,
    task="
    $\\begin{cases}
      4x+6y=10\\\\
      2x+3y=4|\\cdot (-2)
    \\end{cases} \\rightarrow
    +\\begin{cases}
      4x+6y=10\\\\
      -4x-6y=-8
    \\end{cases} \\rightarrow 0x+0y=2.$
    Märgista õige väide:
    \\begin{itemize}
      \\item[\\Circle] Süsteemi lahend on $\\begin{cases}
        x=0\\\\
        y=0
        \\end{cases}$.
      \\item[\\Circle] Süsteemil on lõpmatu hulk lahendeid.
      \\item[\\Circle] Süsteemil lahend puudub.
      \\item[\\Circle] Süsteemi lahend on $\\begin{cases}
        x=1\\\\
        y=1
        \\end{cases}$.
    \\end{itemize}
    "
  ),
  list(
    goal=37,
    level=3,
    task="$$-2x-y=-7.$$
    $$y=$$
    \\begin{itemize}
      \\item[\\Square] $7-2x$.
      \\item[\\Square] $-7$.
    \\end{itemize}
    $$x=-3 \\rightarrow y=\\blank{13}.$$"
  ),
  list(
    goal = 39,
    level = 6,
    task = "Loe teksti ja koosta tekstile vastav võrrand:\\leavevmode\\
    Kolm sõpra Markus, Tõnis ja Karl kulutasid poes taskuvaluutat. Markusel jäi pärast poes käiku valuutat alles \\num{4,5} euro võrra vähem kui Karlil. Karlil jäi valuutat alles kaks korda rohkem kui Tõnisel. Kokku jäi poistel valuutat alles \\num{49,5} eurot.\\leavevmode\\
    Koosta võrrand, mis näitab, kui palju valuutat jäi kokku sõpradel alles peale poes käiku, kui Karlil alles jäänud valuuta hulka esitab arv $x$:
    $$\\underbrace{\\blank{x-4,5}}_\\text{Markus}+\\underbrace{x}_\\text{Karl}+\\underbrace{\\blank{\\frac{x}{4}}}_\\text{Tõnis}=49,5.$$
    Lahenda saadud võrrand ning kirjuta välja võrrandi lahend!\\leavevmode\\
    Võrrandi lahend on $x=\\blank{24}$."
  ),
  list(
    goal=39,
    level=6,
    task="Raamat ja kaustik maksavad kokku \\qty{30}{\\euro}. Raamatulaadal oli sama raamatu hinda alandatud \\qty{25}{\\percent} võrra ja sama kaustiku hinda poole võrra. Nüüd maksid raamat ja kaustik kokku \\qty{21}{\\euro}. Koosta nende tingimuste järgi kahe tundmatuga normaalkujuline lineaarvõrrandisüsteem, kus raamatu hind on $x$\\, \\unit{\\euro} ja vihiku hind $y$\\, \\unit{\\euro}. Märgista sobilik lahendus:
    \\begin{itemize}
      \\item[\\Square] $\\begin{cases}
          x+y=\\blank{30}\\\\
          \\blank{0,75}x+\\blank{0,5}y=\\blank{21}
        \\end{cases}.$
      \\item[\\Square] $\\begin{cases}
          x+y=\\blank{2+}\\\\
          \\blank{-3}x+\\blank{4}y=\\blank{-1}
        \\end{cases}.$
    \\end{itemize}
      "
  ),
  list(
    goal = 41,
    level = 3,
    task = "Uuri tabelit \\@ref(tab:tasks-tables-x-y) ja otsusta, milline võrdus esitab seost muutujate $x$ ja $y$ vahel:
    \\begin{itemize}
      \\item[\\Circle] $y=-12x.$
      \\item[\\Circle] $y=-\\frac{12}{x}.$
      \\item[\\Circle] $y=\\frac{12}{x}.$
      \\item[\\Circle] $y=12x.$
    \\end{itemize}
    Millises punktis lõikab funktsiooni $y=-2x-5$ graafik $y$-telge?\\leavevmode\\
    Funktsiooni graafik lõikab $y$-telge punktis (\\blank{0}; \\blank{-5})."
  ),
  list(
    goal = 41,
    level = 3,
    task = "Millist seost esitab valem $y=-2x-5$?
    \\begin{itemize}
      \\item[\\Circle] Lineaarset seost ehk lineaarfunktsiooni.
      \\item[\\Circle] Võrdelist seost.
      \\item[\\Circle] Pöördvõrdelist seost.
      \\item[\\Circle] Ei esita ühtegi seost..
    \\end{itemize}"
  ),
  list(
    goal = 42,
    level = 4,
    task = "Lineaarfunktsioonide $y=ax-3$ ja $y=4x+3$ graafikud on paralleelsed, kui lineaarliikme kordaja $a=$
    \\begin{itemize}
      \\item[\\Square] 3.
      \\item[\\Square] 4.
    \\end{itemize}"
  ),
  list(
    goal = 42,
    level = 4,
    task = "Joonisel \\@ref(fig:tasks-figures-linear-graphs) on kahe funktsiooni graafikud. Sinine graafik esindab funktsiooni
    \\begin{itemize}
      \\item[\\Square] $y=-2x+2$.
      \\item[\\Square] $y=2x-2$.
      \\item[\\Square] $y=-2x$.
      \\item[\\Square] $y=-0,5x$.
    \\end{itemize}
    Oranž graafik esindab funktsiooni
    \\begin{itemize}
      \\item[\\Square] $y=-2x+2$.
      \\item[\\Square] $y=2x-2$.
      \\item[\\Square] $y=-2x$.
      \\item[\\Square] $y=-0,5x$.
    \\end{itemize}"
  ),
  list(
    goal=42,
    level=4,
    task="Joonisel \\@ref(fig:tasks-figures-graphs) on kahe tundmatuga lineaarvõrrandisüsteeme kujutatud graafiliselt. 
    Märgista iga õige väide sinu poolt vaadates vasema lineaarvõrrandisüsteemi kohta:
    \\begin{itemize}
      \\item[\\Square] Sirged on lõikuvad.
      \\item[\\Square] Süsteemil lahend puudub.
      \\item[\\Square] Süsteemil on üks lahend.
      \\item[\\Square] Süsteemil on lõpmatu hulk lahendeid.
      \\item[\\Square] Sirged on paralleelsed.
      \\item[\\Square] Sirged langevad kokku.
    \\end{itemize}
    Märgista iga õige väide sinu poolt vaadates parempoolse lineaarvõrrandisüsteemi kohta:
    \\begin{itemize}
      \\item[\\Square] Sirged on lõikuvad.
      \\item[\\Square] Süsteemil lahend puudub.
      \\item[\\Square] Süsteemil on üks lahend.
      \\item[\\Square] Süsteemil on lõpmatu hulk lahendeid.
      \\item[\\Square] Sirged on paralleelsed.
      \\item[\\Square] Sirged langevad kokku.
    \\end{itemize}
    "
  ),
  list(
    goal=44,
    level=4,
    task="Kaks kolmnurka on sarnased, kui
    \\begin{itemize}
      \\item[\\Square] ühe kolmnurga kaks külge on võrdelised teise kolmnurga kahe küljega.
      \\item[\\Square] ühe kolmnurga kaks nurka on võrdsed teise kolmnurga kahe nurgaga.
      \\item[\\Square] mõlemad kolmnurgad on võrdkülgsed.
      \\item[\\Square] ühe kolmnurga üks nurk on võrdne teise kolmurga ühe nurgaga ja nende nurkade lähisküljed on võrdelised.
    \\end{itemize}"
  ),
  list(
    goal=44,
    level=4,
    task="Võrdhaarses kolmnurgas $ABC$ on $DE \\parallel AB$, $CD=\\qty{6}{\\centi\\m}$, $EB=\\qty{9}{\\centi\\m}$ ja $AB=\\qty{20}{\\centi\\m} (joonis \\@ref(fig:tasks-figures-similar-triangles).
    $$\\frac{6}{15}=\\frac{DE}{\\blank{AB}}.$$
    Lõigu $DE$ pikkus on \\blank{8}\\ensuremath{\\thinspace}\\unit{\\centi\\m}."
  ),
  list(
    goal=44,
    level=4,
    task="Joonisel \\@ref(fig:tasks-figures-similar-triangles-2) on kolmurgad $ABC$ ja $DFE$ sarnased. Millised tunnuse järgi on kolmurgad sarnased?
    \\begin{itemize}
      \\item[\\Circle] Nurk, külg, nurk.
      \\item[\\Circle] Külg, nurk, külg.
      \\item[\\Circle] Nurk, nurk.
      \\item[\\Circle] Külg, külg, külg.
    \\end{itemize}
    Arvuta sarnasustegur $k$ ja lõigu $EF$ pikkus!
    $$k=\\blank{\\frac{2}{3}}; EF=\\blank{6}\\ensuremath{\\thinspace}\\unit{\\centi\\m}.$$"
  ),
  list(
    goal=44,
    level=4,
    task="Sarnaste hulknurkadega ümbermõõtude suhe võrdub
    \\begin{itemize}
      \\item[\\Circle] alati kahega.
      \\item[\\Circle] alati ühega.
      \\item[\\Circle] sarnasusteguriga.
      \\item[\\Circle] sarnasusteguri ruuduga.
    \\end{itemize}
    Kahe sarnase hulknurga ümbermõõdud on \\qty{10}{\\deci\\m} ja \\qty{20}{\\deci\\m}. Kuidas suhtuvad nende hulknurkade pindalad?\\leavevmode\\
    Hulknurkade pindalade suhe võrdub
    \\begin{itemize}
      \\item[\\Square] \\num{4}'ga.
      \\item[\\Square] $\\frac{1}{4}$'ga.
      \\item[\\Square] \\qty{30}{\\deci\\m}'ga.
    \\end{itemize}"
  ),
  list(
    goal=44,
    level=4,
    task="Joonisel \\@ref(fig:tasks-figures-land-piece) on nelinurkse maatüki plaan plaanimõõduga 1 : 500. Selle maatüki $ABCD$ ümbermõõt plaanil on \\qty{25}{\\centi\\m} ja pindala \\qty{40}{\\square\\centi\\m}. Arvuta maatüki tegelik ümbermõõt meetrites $P$ ja pindala ruutmeetrites $S$:
    \\begin{itemize}
      \\item[\\Square] $P=25 \\times 1:3=\\blank{12500}$\\ensuremath{\\thinspace}$(\\unit{\\m})$.
      \\item[\\Square] $P=25 \\times 500=\\blank{12500}$\\ensuremath{\\thinspace}$(\\unit{\\m})$.
      \\item[\\Square] $S=40 \\times \\blank{250000}=\\num{45}$\\ensuremath{\\thinspace}$(\\unit{\\m\\squared})$.
      \\item[\\Square] $S=40 \\times \\blank{250000}=\\num{10000000}$\\ensuremath{\\thinspace}$(\\unit{\\m\\squared})$.
    \\end{itemize}"
  ),
  list(goal = 45, level = 3, task = "Joonisel \\@ref(fig:tasks-triangle-gravitational-center) on kolmnurk $KLM$. Selle kolmnurga raskuskeset märgib joonisel punkt $O$. Joonesta kolmnurgale mediaanid tippudest $M$ ja $L$!\\leavevmode\\
       Kolmnurga mediaanide lõikepunkt jaotab mediaanid kaheks osaks: küljepoolseks ja tipupoolseks osaks. Küljele $KM$ tõmmatud mediaanist tipupoolne osa on \\qty{18}{\\centi\\m} pikkune. Arvuta mediaani kogupikkus!\\leavevmode\\
       Küljele $KM$ tõmmatud mediaani pikkus on\\leavevmode\\
       \\begin{itemize}
        \\item[\\Square] \\qty{27}{\\centi\\m}.
        \\item[\\Square] \\qty{3,2}{\\centi\\m}.
      \\end{itemize}
       "
  ),
  list(
    goal = 45,
    level = 3,
    task = "Joonisel \\@ref(fig:tasks-trapecoid-height-triangle) kujutatud kujund koosneb trapetsist $ABDE$ ja kolmnurgast $BCD$. Joonesta trapetsile punktist $A$ kõrgus!\\leavevmode\\
    Arvuta kujundi pindala!\\leavevmode\\
    Trapetsi pikem alus on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] \\num{7}\\ensuremath{\\thinspace}pikkusühikut.
      \\item[\\Square] \\num{5,1}\\ensuremath{\\thinspace}pikkusühikut.
      \\item[\\Square] \\num{8}\\ensuremath{\\thinspace}pikkusühikut.
    \\end{itemize}
    Trapetsi pindala on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] \\num{16,5}\\ensuremath{\\thinspace}pindalaühikut.
      \\item[\\Square] \\num{28}\\ensuremath{\\thinspace}pindalaühikut.
      \\item[\\Square] \\unit{\\centi\\m}\\ensuremath{\\thinspace}pindalaühikut.
    \\end{itemize}
    Kujundi $ABCD$ pindala on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] \\num{27}\\ensuremath{\\thinspace}pindalaühikut.
      \\item[\\Square] \\num{40}\\ensuremath{\\thinspace}pindalaühikut.
      \\item[\\Square] \\unit{\\centi\\m}\\ensuremath{\\thinspace}pindalaühikut.
    \\end{itemize}
    "
  ),
  list(
    goal = 45,
    level = 3,
    task = "Vaata joonist \\@ref(fig:tasks-figures-multiangle) ja vali õige valikvastus!\\leavevmode\\
    Joonisel on
    \\begin{itemize}
      \\item[\\Square] korrapärane kuusnurk
      \\item[\\Square] korrapärane viissnurk
      \\item[\\Square] mittekorrapärane kuusnurk
      \\item[\\Square] mittekorrapärane viissnurk
    \\end{itemize}
    $ABCDE$.
    Joonesta viisnurgale diagonaalid punktist $A$.
    Viisnurga sisenurkade summa arvutatakse avaldise $(\\blank{n-2}) \\cdot 180 \\degree$ abil."
  ),
  list(
    goal = 45,
    level = 3,
    task = "Joonisel \\@ref(fig:tasks-figures-parallelogram) on rööpkülik $KLMN$.\\leavevmode\\
    Rööpküliku külje $KN$ pikkus on \\blank{3}\\,\\unit{\\centi\\m} ja nurga $N$ suurus on
    \\begin{itemize}
      \\item[\\Square] 140\\unit{\\degree}.
      \\item[\\Square] 50\\unit{\\degree}.
    \\end{itemize}
    Joonesta rööpkülikule punktist $N$ kõrgus!\\leavevmode\\
    Kui kujundi kõrgus on $h=\\qty{2,4}{\\centi\\m}$, siis kujundi pindala $S=$
    \\begin{itemize}
      \\item[\\Square] 12
      \\item[\\Square] \\num{9,8}
      \\item[\\Square] \\num{4,8}
    \\end{itemize}
    \\unit{\\square\\centi\\m}."
  ),
  list(
    goal = 45,
    level = 3,
    task = "Joonisel \\@ref(fig:tasks-figures-rhombus) on romb $ABCD$.\\leavevmode\\
    Uuri joonist ja märgista, kui väide on tõene:
    \\begin{itemize}
      \\item[\\Square] Romb on korrapärane nelinurk.
      \\item[\\Square] Rombi diagonaalid poolitavad teineteist.
      \\item[\\Square] Rombi diagonaalid on risti.
    \\end{itemize}"
  ),
  list(
    goal = 45,
    level = 3,
    task = "Rombi diagonaalide pikkused on \\qty{2}{\\deci\\m} ja \\qty{8}{\\deci\\m}.\\leavevmode\\
    Rombi pindala on
    \\begin{itemize}
      \\item[\\Square] 6
      \\item[\\Square] 8
    \\end{itemize}
    \\unit{\\deci\\m}."
  ),
  list(
    goal=45,
    level=3,
    task="Mõõtmisel saadi, et korrapärase kuusnurga $ABCDEF$ ühe külje pikkus on ligikaudu \\qty{4}{\\deci\\m} ja apoteem on ligikaudu \\qty{3,5}{\\deci\\m} (joonis \\@ref(fig:tasks-figures-multiangle-equilateral)).\\leavevmode\\
    Lõigu $AB$ ligikaudne pikkus on
    \\begin{itemize}
      \\item[\\Square] \\qty{4}{\\deci\\m}.
      \\item[\\Square] \\qty{0,8}{\\deci\\m}.
    \\end{itemize}
    Lõigu $OH$ ligikaudne pikkus on
    \\begin{itemize}
      \\item[\\Square] \\qty{3,5}{\\deci\\m}.
      \\item[\\Square] \\qty{1,2}{\\deci\\m}.
    \\end{itemize}
    Kuusnurga $ABCDEF$ ligikaudne ümbermõõt on
    \\begin{itemize}
      \\item[\\Square] \\qty{24}{\\deci\\m}.
      \\item[\\Square] \\qty{3,6}{\\deci\\m}.
    \\end{itemize}
    Kolmnurga $ABO$ ligikaudne pindala on \\blank{\\num{7}}\\ensuremath{\\thinspace}\\unit{\\square\\deci\\m}.
    Kuusnurga $ABCDEF$ ligikaudne pindala on
    \\begin{itemize}
      \\item[\\Square] \\qty{42}{\\deci\\m}.
      \\item[\\Square] \\qty{12}{\\deci\\m}.
      \\item[\\Square] \\qty{0,936}{\\deci\\m}.
    \\end{itemize}
    "
  ),
  list(
    goal = 46,
    level = 3,
    task = "Pealt lahtise risttahukakujulise anuma ruudukujulise põhja ühe serva pikkus on \\qty{5}{\\centi\\m}. Anuma kõrgus on \\qty{8}{\\deci\\m}. Mitu liitrit vett mahutab see anum?
    \\begin{itemize}
      \\item[\\Circle] 40
      \\item[\\Circle] 0,2
      \\item[\\Circle] 2
      \\item[\\Circle] 0,4
    \\end{itemize}
    \\unit{\\liter}."
  ),
  list(goal = 48, level = 1, task = "Joonisel \\@ref(fig:tasks-triangle-central-line) on kolmnurk $ABC$, millesse on joonestatud lõik $a$. Uuri joonist ning vali õiged väited valikvastuste seast lõigu $a$ kohta ja täida lünk:\\leavevmode\\
       Lõik $a$ on kolmnurga $ABC$\\leavevmode\\
    \\begin{itemize}
      \\item[\\Circle] kesklõik.
      \\item[\\Circle] keskristsirge.
      \\item[\\Circle] küljepoolitaja.
      \\item[\\Circle] mediaan.
      \\item[\\Circle] on võrdhaarne.
    \\end{itemize}
    Lõik $a$ on kolmnurga\\leavevmode\\
    \\begin{itemize}
      \\item[\\Circle] küljega $BC$ risti.
      \\item[\\Circle] küljega $AC$ \\qty{30}{\\degree} nurga all.
      \\item[\\Circle] küljega $AB$ paralleelne.
      \\item[\\Circle] küljega $AB$ lõikuv.
      \\item[\\Circle] kõrgus.
      \\item[\\Circle] mediaan.
    \\end{itemize}
    Lõigu $a$ pikkus on\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] 3\\ensuremath{\\thinspace}pikkusühikut.
      \\item[\\Square] $\\qty{2}{\\centi\\m}-\\qty{20}{\\milli\\m}$\\ensuremath{\\thinspace}pikkusühikut.
    \\end{itemize}
    "),
  list(goal = 48, level = 1, task = "Kolmnurga külgede pikkused on \\qty{4}{\\centi\\m}, \\qty{6}{\\centi\\m} ja \\qty{7}{\\centi\\m}. Arvuta kolmnurga kesklõikudest moodustatud kolmnurga ümbermõõt!\\leavevmode\\
       Kesklõikudest moodustunud komnurga ümbermõõt on $P=$\\leavevmode\\
       \\begin{itemize}
        \\item[\\Square] \\qty{8,5}{\\centi\\m}.
        \\item[\\Square] \\qty{17}{\\centi\\m}.
      \\end{itemize}
       "),
  list(
    goal = 48,
    level = 1,
    task = "Joonisel \\@ref(fig:tasks-trapecoid-central-line) on olemas trapetsi kõikide külgede pikkused ja kõikid ekülgede keskpunktid.\\leavevmode\\
    Joonesta trapetsi kesklõik!\\leavevmode\\
    Arvuta kesklõigu $K$ pikkus! Märgista, kui väide on õige!\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] $K=\\frac{\\qty{5,1}{\\centi\\m} + \\qty{8,9}{\\centi\\m}}{2}=\\qty{7}{\\centi\\m}$.
      \\item[\\Square] $K=\\frac{\\qty{3,4}{\\centi\\m} + \\qty{3,6}{\\centi\\m}}{2}=\\qty{3,5}{\\centi\\m}$.
    \\end{itemize}
    "
  ),
  list(
    goal = 48,
    level = 1,
    task = "Joonisel \\@ref(fig:tasks-trapecoid-diagonal) on trapetsikujuline maatükk, mille pikem alus on \\qty{1000}{\\m}. Mööda trapetsikujulise maatüki kesklõiku jookseb kuivenduskraav. Naabrite majad paiknevad trapetsi tippudes nii, et kõige lühem jalgtee naabrini läheb mööda trapetsi diagonaali. Kuivenduskraav ja jalgtee lõikuvad nii, et lühem osa kuivenduskraavist on \\qty{300}{\\m} (vaata joonist). Veel on teada, et maatüki kahe paralleelse külje vaheline kaugus on \\qty{450}{\\m}.\\leavevmode\\
    Märgista, kui väide on õige:\\leavevmode\\
    \\begin{itemize}
      \\item[\\Square] Kuivenduskraavi pikkus on $k=300+\\num{500}=\\num{800}\\ensuremath{\\thinspace}(\\unit{\\m})$.
      \\item[\\Square] Maatüki lühema aluse pikkus on \\qty{600}{\\m}.
      \\item[\\Square] Maatüki pindala on \\qty{36}{\\hectare}.
      \\item[\\Square] Kuivenduskraavi pikkus on $k=300+\\num{1000}=\\num{1300}\\ensuremath{\\thinspace}(\\unit{\\m})$.
      \\item[\\Square] Maatüki lühema aluse pikkus on \\qty{220}{\\m}.
      \\item[\\Square] Kuivenduskraavi pikkus on $k=300+\\num{450}=\\num{750}\\ensuremath{\\thinspace}(\\unit{\\m})$.
      \\item[\\Square] Maatüki lühema aluse pikkus on \\qty{1000}{\\m}.
      \\item[\\Square] Maatüki pindala on \\qty{18}{\\hectare}.
      \\item[\\Square] Maatüki lühema aluse pikkus on \\qty{100}{\\m}.
      \\item[\\Square] Maatüki pindala on \\qty{1500}{\\hectare}.
    \\end{itemize}
    "
  ),
  list(
    goal = 50,
    level = 4,
    task = "$\\num{0.0001}=10^{\\blank{-4}}.$"
  ),
  list(
    goal = 50,
    level = 4,
    task = "$100000=10^{\\blank{4}}.$"
  ),
  list(
    goal = 51,
    level = 4,
    task = "Rööpkülikuks nimetatakse nelinurka, mille
    \\begin{itemize}
      \\item[\\Square] nurgad on võrdse suurusega.
      \\item[\\Square] küljed on võrdse pikkusega.
      \\item[\\Square] vastasnurgad on võrdsed.
      \\item[\\Square] vastasküljed on paralleelsed.
    \\end{itemize}
    Teoreemi sõnastuses teoreemi eeldus algab sõnaga
    \\begin{itemize}
      \\item[\\Circle] ja
      \\item[\\Circle] kui
      \\item[\\Circle] ei
      \\item[\\Circle] siis
    \\end{itemize}
     ja teoreemi väide algab sõnaga
   \\begin{itemize}
      \\item[\\Circle] ja.
      \\item[\\Circle] kui.
      \\item[\\Circle] ei.
      \\item[\\Circle] siis.
    \\end{itemize}"
  )
)

# Putting together all the tasks

tasks <- c(
  tasks
)

# print(" tasks ")
# View(tasks)
# print(" lõpp tasks ")
# })



# Kontrolli, kas tasks sees on kusagil vektor task-väljal
# probleemsed <- sapply(tasks, function(x) length(x$task) > 1)
# which(probleemsed) # annab indeksi, kus probleem tekib
# print(" proble ")
# print(tasks[probleemsed]) # kuvab täpse probleemi koha
# print(" lõpp proble ")

dataframe_tasks <- do.call(rbind, lapply(tasks, as.data.frame, stringsAsFactors = FALSE))
number_goals <- length(goals)

librarian::shelf(c(
  "dplyr"
))

number_of_pupils <- 64

goals_in_use <- unique(dataframe_tasks$goal)
# print(" dataframe_tasks ")
# print(dataframe_tasks)
# print(" lõpp dataframe_tasks ")
number_of_goals_in_use <- length(goals_in_use)
random_sample_df <- function(df, new_size) { # 64
  base_size <- floor(new_size / nrow(df))  
  remaining <- new_size %% nrow(df)

  repeated_df <- df[rep(1:nrow(df), each = base_size), , drop = FALSE]

  extra_rows <- df[sample(1:nrow(df), remaining, replace = FALSE), , drop = FALSE]

  final_df <- rbind(repeated_df, extra_rows)
  final_df <- final_df[sample(1:nrow(final_df)), , drop = FALSE]

  return(final_df)
}

number_of_tasks_at_level_per_pupil <- 8 # 8
# number_of_tasks <- number_of_pupils * number_of_tasks_at_level_per_pupil
 
number_of_tasks <- nrow(dataframe_tasks)
df_segatud <- dataframe_tasks[sample(number_of_tasks), ]
arranged_sampled_tasks <- arrange(df_segatud, goal, level)
# print(" arranged_sampled_tasks ")
# View(arranged_sampled_tasks)
# print(" lõpp arranged_sampled_tasks ")
# })



# chosen_tasks <- c()
# # })
# 
# 
# for (index_of_task in 1:number_of_tasks) { # 1-512
# 
#   for (index in 1:number_of_goals_in_use) {
#     tasks_of_goal <- subset(arranged_sampled_tasks, goals_in_use[index] == `goal`)
#     levels_in_use <- unique(tasks_of_goal$level)
#     number_of_levels_in_use <- length(levels_in_use)
#     
#     for (index_of_level in 1:number_of_levels_in_use) {
#       tasks_at_level <- subset(tasks_of_goal, levels_in_use[index_of_level] == `level`)
#       print(" number tasks_at_level ")
#       print(goals_in_use[index])
#       print(levels_in_use[index_of_level])
#       print(nrow(tasks_at_level))
#       print(" lõpp number tasks_at_level ")
#       # sampled_tasks_at_level <- random_sample_df(df = tasks_at_level, new_size = number_of_pupils)
#       if (number_of_tasks_at_level_per_pupil > nrow(tasks_at_level)) {
#         number_of_chosen_tasks_at_level <- nrow(tasks_at_level)
#       } else {
#         number_of_chosen_tasks_at_level <- number_of_tasks_at_level_per_pupil
#       }
#       if (length(chosen_tasks) > 0) {
#         chosen_tasks <- rbind(chosen_tasks, tasks_at_level[1:number_of_chosen_tasks_at_level, ])
#       } else {
#         chosen_tasks <- tasks_at_level[1:number_of_chosen_tasks_at_level, ]
#       }
#       
#     }
#       
#   }
#   
# }
# print(" unique sampled_tasks ")
# print(unique(sampled_tasks$task[grep("c\\(", sampled_tasks$task)]))
# print(" lõpp unique ")
# probleemsed_taskid <- sampled_tasks[grep("c\\(", sampled_tasks$task), ]
# print(probleemsed_taskid)
# print(" täitsa lõpp unique ")
# sampled_tasks <- arrange(sampled_tasks, goal, level)
# })

```




## Üks ülesanne õpilase kohta

```{r label="list-of-tasks-one-per-pupil", echo=FALSE, results='asis'}
# profvis({

for (index_of_pupil in 1:number_of_pupils) {
  cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))

  for (index in 1:number_of_goals_in_use) {
    # print(" index_goals_in_use ")
    # print(index)
    # print(" lõpp index_goals_in_use ")
    cat(paste(
      "**\\color[hsb]{0.",
      goals[[goals_in_use[index]]]$level - 1,
      ", 1, .75}{Õpiväljund:}** Õpilane ",
      goals[[goals_in_use[index]]]$goal,
      ".\n\n", 
      sep = ""
    ))
    
    # tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
    # levels_in_use <- unique(x = tasks_of_goal$level)
    # number_of_levels_in_use <- length(levels_in_use)

    for (index_of_levels in 1:6) {
      tasks_goal_level <- subset(arranged_sampled_tasks, index_of_levels == `level` & goals_in_use[index] == `goal`)
      number_of_tasks_goal_level <- nrow(tasks_goal_level)
      if (number_of_tasks_goal_level > 0) {
        
        cat(
          "**",
          index_of_levels,
          ". taseme ülesanne:** ",
          sep = ""
        )
      
        cat(tasks_goal_level[index_of_pupil %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
      }

      # tasks_at_level <- subset(
      #   tasks_of_goal,
      #   levels_in_use[index_of_levels] == `level`
      # )
    }

  }

}

# })

```

## Mitu ülesannet õpilase kohta

```{r label="tasks-many-per-pupil", echo=FALSE, results='asis'}
# profvis({
# 
# for (index_of_pupil in 1:number_of_pupils) {
#   cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))
# 
#   for (index in 1:number_of_goals_in_use) {
#     # print(" index_goals_in_use ")
#     # print(index)
#     # print(" lõpp index_goals_in_use ")
#     cat(paste(
#       "**\\color[hsb]{0.",
#       goals[[goals_in_use[index]]]$level - 1,
#       ", 1, .75}{Õpiväljund:}** Õpilane ",
#       goals[[goals_in_use[index]]]$goal,
#       ".\n\n", 
#       sep = ""
#     ))
#     
#     # tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
#     # levels_in_use <- unique(x = tasks_of_goal$level)
#     # number_of_levels_in_use <- length(levels_in_use)
# 
#     for (index_of_levels in 1:5) {
#       tasks_goal_level <- subset(arranged_sampled_tasks, index_of_levels == `level` & goals_in_use[index] == `goal`)
#       number_of_tasks_goal_level <- nrow(tasks_goal_level)
#       if (number_of_tasks_goal_level > 1) {
#         
#         cat(
#           "**",
#           index_of_levels,
#           ". taseme ülesanded:**\n\n",
#           sep = ""
#         )
#       
#         # cat(tasks_goal_level[index_of_pupil %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
#       } else if (number_of_tasks_goal_level > 0) {
#         
#         cat(
#           "**",
#           index_of_levels,
#           ". taseme ülesanne:** ",
#           sep = ""
#         )
#         
#       }
#       
#       if (number_of_tasks_goal_level > 0) {
#         max_number_of_tasks <- 8 - 1
#         # cat("\\begin{enumerate}[label=\\alph*.]\n")
#         for (index_of_task_goal_level in 0:max_number_of_tasks) {
#           cat(index_of_pupil, "-", index, "-", index_of_levels, "-", index_of_task_goal_level, ". ", tasks_goal_level[(index_of_pupil + index_of_task_goal_level) %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
#         }
#         # cat("\\end{enumerate}\n")
#       }
# 
#       # tasks_at_level <- subset(
#       #   tasks_of_goal,
#       #   levels_in_use[index_of_levels] == `level`
#       # )
#     }
# 
#   }
# 
# }
# })
# current_pupil <- 1
# 
# for (index_of_pupil in 1:number_of_pupils) {
#   cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))
# 
#   for (index in 1:number_of_goals_in_use) {
#     
#     cat(paste(
#       "**\\color[hsb]{0.",
#       goals[[goals_in_use[index]]]$level - 1,
#       ", 1, 1}{Õpiväljund:}** Õpilane ",
#       goals[[goals_in_use[index]]]$goal,
#       ".\n\n", 
#       sep = ""
#     ))
# 
#     tasks_of_goal <- subset(chosen_tasks, goals_in_use[index] == `goal`)
#     levels_in_use <- unique(x = tasks_of_goal$level)
#     number_of_levels_in_use <- length(levels_in_use)
# 
#     for (index_of_levels in 1:number_of_levels_in_use) {
#           
#       cat(
#         "**",
#         levels_in_use[index_of_levels],
#         ". taseme ülesanded:**\n\n ",
#         sep = ""
#       )
# 
#       tasks_at_level <- subset(
#         tasks_of_goal,
#         levels_in_use[index_of_levels] == `level`
#       )
#       
#       number_of_tasks_at_level <- nrow(tasks_at_level)
#       last_task_for_pupil <- current_pupil + number_of_tasks_at_level_per_pupil - 1
#       
#       for (index_of_task in current_pupil:last_task_for_pupil) {
#         cat(index_of_task, ". ", tasks_at_level[index_of_task, ]$task, "\n\n", sep = "")
#       }
#       
#       current_pupil <- current_pupil + number_of_tasks_at_level_per_pupil
#     }
# 
#   }
# 
# }

```

## Tabelid

```{r label="tasks-tables-x-y", echo=FALSE}
rownames <- c("x", "y"
              )
data <- data.frame(
  c( # 1
  	-4, # x
  	3 # y
  ),
  c( # 2
  	2, # x
  	-6 # y
  ),
  c( # 3
  	3, # x
  	-4 # y
  )
)

data_frame <- data[1]
for (data_identifier in 2:3) {
  data_frame <- cbind(data_frame, data[data_identifier])
}

colnames(data_frame) <- seq(from=1, to=ncol(data_frame))
rownames(data_frame) <- rownames

table <- print_table(
  table = data_frame,
  caption = "Muutujate $x$ ja $y$ väärtused."
)

table

```

```{r label="tasks-tables-fractions", echo=FALSE}
data <- data.frame(
  c( # 1
  	"$\\frac{1}{2}$", # harilik osamäär
  	"$\\num{0,5}$", # kümnendosamäär
  	"\\blank{\\qty{50}{\\percent}}" # protsentides
  ),
  c( # 2
  	"$\\frac{1}{4}$", # harilik osamäär
  	"$\\blank{\\num{0,25}}$", # kümnendosamäär
  	"\\qty{25}{\\percent}" # protsentides
  ),
  c( # 3
  	"$\\blank{\\frac{2}{5}}$", # harilik osamäär
  	"$\\num{0,4}$", # kümnendosamäär
  	"\\qty{40}{\\percent}" # protsentides
  ),
  c( # 4
  	"$\\blank{\\frac{3}{4}}$", # harilik osamäär
  	"$\\num{0,75}$", # kümnendosamäär
  	"\\blank{\\qty{75}{\\percent}}" # protsentides
  )
)

data_frame <- data

rownames(data_frame) <- c(
  "Harilik osamäär",
  "Kümnendosamäär",
  "Protsentides"
)

colnames(data_frame) <- c(1:length(data_frame))

table <- print_table(
  table = data_frame,
  caption = "Osamäärade erinevad esitusviisid.",
  do_i_transpose = TRUE
)

table

```

\clearpage

## Joonised

```{r label = "tasks-sector-diagram", echo=FALSE, fig.cap = "Roosioksa talu pererahva maade jaotus."}
include_external_graphics("rmd/sektor1.png")

```

```{r label = "tasks-discount-book", echo=FALSE, fig.cap = "Allahinnatud raamat."}
include_external_graphics("rmd/reisijuht.png")

```

```{r label = "tasks-lines-angles", echo=FALSE, fig.cap = "Kahe sirge lõikamisel kolmandaga nurgad."}
include_external_graphics("rmd/Def2.png")

```

```{r label = "tasks-lines-side-angles", echo=FALSE, fig.cap = "Kahe sirge lõikamisel kolmandaga kõrvunurgad."}
include_external_graphics("rmd/joon2.png")

```

```{r label = "tasks-lines-top-angles", echo=FALSE, fig.cap = "Kahe sirge lõikamisel kolmandaga tippnurgad."}
include_external_graphics("rmd/joon4.png")

```

```{r label = "tasks-lines-skewed-angles", echo=FALSE, fig.cap = "Kahe sirge lõikamisel kolmandaga põiknurgad."}
include_external_graphics("rmd/joon1.png")

```

```{r label = "tasks-lines-close-angles", echo=FALSE, fig.cap = "Kahe sirge lõikamisel kolmandaga lähisnurgad."}
include_external_graphics("rmd/joon3.png")

```

```{r label = "tasks-triangle-central-line", echo=FALSE, fig.cap = "Kolmnurga teatud lisajoon."}
include_external_graphics("rmd/DEF3.png")

```

```{r label = "tasks-triangle-gravitational-center", echo=FALSE, fig.cap = "Kolmnurga raskuskese."}
include_external_graphics("rmd/DEF5.png")

```

```{r label = "tasks-trapecoid-height-triangle", echo=FALSE, fig.cap = "Kolmnurgast ja trapetsist moodustuv kujund."}
include_external_graphics("rmd/trapets.png")

```

```{r label = "tasks-trapecoid-central-line", echo=FALSE, fig.cap = "Trapets kesklõiguta."}
include_external_graphics("rmd/trapets_DEF8.png")

```

```{r label = "tasks-trapecoid-diagonal", echo=FALSE, fig.cap = "Trapets diagonaaliga."}
include_external_graphics("rmd/DEF9.png")

```

```{r label = "tasks-figures-linear-graphs", echo=FALSE, fig.cap = "Lineaarsed graafikud."}
include_external_graphics("rmd/fun6_joonis.png")

```

```{r label = "tasks-figures-multiangle", echo=FALSE, fig.cap = "Mitme nurgaga kujund."}
include_external_graphics("rmd/hlkn1_joonis.png")

```

```{r label = "tasks-figures-parallelogram", echo=FALSE, fig.cap = "Rööpkülik."}
include_external_graphics("rmd/hlkn3_joonis.png")

```

```{r label = "tasks-figures-rhombus", echo=FALSE, fig.cap = "Romb."}
include_external_graphics("rmd/hlkn5_joonis.png")

```

```{r label = "tasks-figures-circle-central-border-angle", echo=FALSE, fig.cap = "Sisenurkadega ring."}
include_external_graphics("rmd/RJKH1.png")

```

```{r label = "tasks-figures-circle-central-2-border-angle", echo=FALSE, fig.cap = "Kaks nurka ringjoonelt."}
include_external_graphics("rmd/RJKH2.png")

```

```{r label = "tasks-figures-circle-tangent", echo=FALSE, fig.cap = "Ring puutujatega."}
include_external_graphics("rmd/RJK3_uus.png")

```

```{r label = "tasks-figures-triangles-circles", echo=FALSE, fig.cap = "Kolmnurgad sisejoontega."}
include_external_graphics("rmd/RJK4.png")

```

```{r label = "tasks-figures-multiangle-equilateral", echo=FALSE, fig.cap = "Hulknurk."}
include_external_graphics("rmd/RJKH5.png")

```

```{r label = "tasks-figures-similar-triangles", echo=FALSE, fig.cap = "Sarnased kolmnurgad."}
include_external_graphics("rmd/KSAR2_uus.png")

```

```{r label = "tasks-figures-similar-triangles-2", echo=FALSE, fig.cap = "Kaks sarnast kolmnurka."}
include_external_graphics("rmd/KSA3.png")

```

```{r label = "tasks-figures-land-piece", echo=FALSE, fig.cap = "Maatükk."}
include_external_graphics("rmd/KSA5_2.png")

```

```{r label = "tasks-figures-area-of-shape", echo=FALSE, fig.cap = "Kujundi pindala."}
include_external_graphics("rmd/HULK6.png")

```

```{r label = "tasks-figures-graphs", echo=FALSE, fig.cap = "Graafikud."}
include_external_graphics("rmd/lvs3.png")

```
