# Voltimine

2025-09-23 õppesessioonis mind, kalmerit, pole, mistõttu õpilased valmistavad stereomeetrilised kujundid mitmevärvilistest paberilehtedest, mis on õpetaja laua kõige alumises sahtlis. Seal on ka eri kujundite voltimisjuhised. Valmistamiseks on vaja neid paberilehti ja kääre, mis tuleb endal kaasa võtta. Kogu rühma peale tuleb valmistada võrdselt igat liiki kujundeid, nii et oleks kõiki kujundite liike. Iga valmis kujundi peale tuleb kirjutada seda kujundit valmistanud õpilaste nimed. Märgin puudujaks iga õpilase, kelle nime pole ühelgi kujundil. Õpilased võivad kujundeid teha üksi või koos: nt üks valmistab ühe kujundi jupid, teine samal ajal teise kujundi jupid, kolmas...

Voltimises tuleb olla võimalikult täpne, sest vähekegi vale volt võib mõjutada, et pärast ei saa kujundit kokku.

Pärast voltimist panevad õpilased kõik vahendid sinna tagasi, kust nad need võtsid.

Iga valmis kujundi peale tuleb kaheksandal tasemel märkida ka selle kujundi ruumala ja välispindala, üheksandal tasemel, millega on ajalooliselt seda kujundit seostatud ja näide keemilisest ühendist, milles aatomid paiknevad omavahel nagu selle kujundi tipud.

Kaheksanda taseme õpilased panevad oma kujundid akna kõrvale riiulile, üheksanda taseme õpilased tõmbekapi kõrvale kapi peale.

