# Tulemused matemaatikas

## Õpiväljundid

```{r label="goals", echo=FALSE, results='asis'}
for (index in 1:number_of_goals_in_use) {
  cat(paste(
    "**\\color[hsb]{0.",
    goals[[goals_in_use[index]]]$level - 1,
    ", 1, .75}{",
    goals_in_use[index],
    ". õpiväljund:}** Õpilane ",
    goals[[goals_in_use[index]]]$goal,
    ".\n\n", 
    sep = ""
  ))
}

```

## Saavutatused

Kaheksanda taseme õpilaste saavutatused on esitatud tabelis \@ref(tab:targets-8).

```{r label="targets-8", echo=FALSE}
classes_8_grades <- data.frame(
  c( # 1
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 2
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  
  ),
  c( # 3
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  
  ),
  c( # 4
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 5
  	1, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	1, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 6
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 7
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 8
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 9
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 10
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 11
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 12
  	1, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	1, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 13
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 14
  	1, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 15
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 16
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 17
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 18
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 19
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 20
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 21
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 22
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 23
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 24
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 25
  	1, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	1, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 26
  	1, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	1, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 27
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 28
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 29
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 30
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 31
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 32
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 33
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 34
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 35
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 36
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  ),
  c( # 37
  	NA, # Andrei Aksjonov
  	NA, # Arseni Badanin
  	NA, # Sergo Klišin
  	NA, # Ruvim Korepanov
  	NA, # Arina Lisogor
  	NA, # Olesja Makarova
  	NA, # Artjom Malinin
  	NA, # Maksim Mihhailov
  	NA # Nikita Timakin
  )
)

included_goals <- c(
  12,
  14,
  25,
  26
)

data_frame <- classes_8_grades[5]
for (goal_identifier in included_goals) {
  data_frame <- cbind(data_frame, classes_8_grades[goal_identifier])
}

colnames(data_frame) <- c(5, included_goals)

rownames(data_frame) <- names_8
table <- print_table(
  table = data_frame,
  caption = "Kaheksanda taseme õpilaste saavutatud õpiväljundid."
) %>% landscape()

table

```

<!-- \begin{landscape} -->

Üheksanda taseme õpilaste saavutatused on esitatud tabelis \@ref(tab:targets-9).

```{r label="targets-9", echo=FALSE}
classes_9_grades <- data.frame(
  c( # 1
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 2
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	1, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 3
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	1, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 4
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 5
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 6
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 7
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 8
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 9
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 10
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 11
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 12
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 13
  	NA, # Margus Evart
  	1, # Mikaela Galperman
  	1, # Valerija Korenkova
  	1, # Dmitri Litvinenko
  	1, # Margarita Mussijenko
  	1, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	1, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	1, # Ivan Timakin
  	NA, # Evelina Tolli
  	1, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 14
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 15
  	NA, # Margus Evart
  	1, # Mikaela Galperman
  	1, # Valerija Korenkova
  	1, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	1, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	1, # Angelina Solovjova
  	1, # Sofia Zhuravleva
  	1, # Ivan Timakin
  	NA, # Evelina Tolli
  	1, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 16
  	NA, # Margus Evart
  	1, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	1, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	1, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 17
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 18
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 19
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 20
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 21
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 22
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 23
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 24
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 25
  	NA, # Margus Evart
  	1, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 26
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 27
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 28
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 29
  	NA, # Margus Evart
  	1, # Mikaela Galperman
  	1, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 30
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	1, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 31
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 32
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 33
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 34
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 35
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 36
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 37
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 38
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 39
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	1, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	1, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 40
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 41
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 42
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 43
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 44
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 45
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 46
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 47
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 48
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 49
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 50
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	NA, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  ),
  c( # 51
  	NA, # Margus Evart
  	NA, # Mikaela Galperman
  	NA, # Valerija Korenkova
  	NA, # Dmitri Litvinenko
  	1, # Margarita Mussijenko
  	NA, # Zahar Orikovi
  	NA, # Jekaterina Plotnikova
  	NA, # Veniamin Postolenko
  	NA, # Angelina Solovjova
  	NA, # Sofia Zhuravleva
  	NA, # Ivan Timakin
  	NA, # Evelina Tolli
  	NA, # Martin Tolli
  	NA, # Ilja Tsvek
  	NA, # Maia Tukkia
  	NA # Arina Vatševskihh
  )
)

included_goals <- c(
  3,
  5,
  13,
  15,
  16,
  25,
  29,
  30,
  37,
  39,
  51
)

data_frame <- classes_9_grades[2]
for (goal_identifier in included_goals) {
  data_frame <- cbind(data_frame, classes_9_grades[goal_identifier])
}

colnames(data_frame) <- c(2, included_goals)

rownames(data_frame) <- names_9
table <- print_table(
  table = data_frame,
  caption = "Üheksanda taseme õpilaste saavutatud õpiväljundid matemaatikas."
) %>% landscape()

table

```

<!-- \end{landscape} -->
