# Keemia lähtetest

```{r label="tasks-chemistry", echo=FALSE, results='asis'}
goals <- list(
  list( # K1
    goal = "järgib laboris katseid tehes ja argielus kemikaale kasutades ohutusnõudeid",
    level = 3
  ),
  list( # K2
    goal = "tunneb tähtsamaid laborivahendeid ja kasutab neid praktilisi töid tehes õigesti",
    level = 3
  ),
  list( # K3
    goal = "eristab lahuseid ja pihuseid ning valmistab neid, toob näiteid lahuste ja pihuste kohta looduses ning igapäevaelus",
    level = 3
  ),
  list( # K4
    goal = "selgitab aatomi ehitust, kasutab keemiliste elementide tähiste leidmiseks, aatomi ehituse kirjeldamiseks ja elektronskeemi koostamiseks keemiliste elementide perioodilisustabelit",
    level = 3
  ),
  list( # K5
    goal = "eristab liht- ja liitaineid ning selgitab aine valemi põhjal aine koostist",
    level = 3
  ),
  list( # K6
    goal = "teab keemiliste elementide liigitamist metallilisteks ja mittemetallilisteks elementideks ning väärisgaasideks, otsib internetist näiteid metallide ja mittemetallide kasutamise kohta igapäevaelus ning võrdleb nende omadusi",
    level = 4
  ),
  list( # K7
    goal = "võrdleb hapniku ja vesiniku põhilisi omadusi",
    level = 4
  ),
  list( # K8
    goal = "teab keemiliste reaktsioonide esilekutsumise võimalusi, tunneb ära keemilise reaktsiooni toimumise iseloomulike tunnuste järgi",
    level = 2
  ),
  list( # K9
    goal = "teab süsinikuühendite paljususe põhjusi",
    level = 2
  ),
  list( # K10
    goal = "koostab süsinikuühendite struktuurivalemeid ja molekulimudeleid etteantud aatomite (C, H, O) arvu järgi, eristab lineaarset, hargnenud ja tsüklilist süsinikahelat",
    level = 3
  ),
  list( # K11
    goal = "lahendab lahuse protsendilisel koostisel põhinevaid arvutusülesandeid",
    level = 3
  ),
  list( # K12
    goal = "selgitab temperatuuri mõju gaaside ning (enamiku) soolade lahustuvusele vees, kasutab ainete lahustuvuse graafikut ja lahustuvustabelit, et leida vajalikku infot ning teha arvutusi ja järeldusi",
    level = 4
  ),
  list( # K13
    goal = "teeb arvutusi aine hulga, massi ja gaasi ruumala vaheliste seoste alusel, kasutab korrektselt vastavaid ühikuid ning põhjendab loogiliselt arvutuskäike",
    level = 4
  ),
  list( # K14
    goal = "analüüsib keemilise reaktsiooni võrrandis sisalduvat kvalitatiivset ja kvantitatiivset infot, mõistab ainete massi jäävust keemilistes reaktsioonides",
    level = 4
  ),
  list( # K15
    goal = "koostab süsivesinike ja etanooli täieliku põlemise reaktsioonivõrrandeid",
    level = 4
  ),
  list( # K16
    goal = "selgitab hapniku rolli põlemisreaktsioonides ning eluslooduses, analüüsib osoonikihi tähtsust ja lagunemist saastamise tagajärjel",
    level = 4
  ),
  list( # K17
    goal = "kogub gaasi, valides sobiva võtte lähtuvalt gaasi lahustuvusest vees ja gaasi tihedusest võrreldes õhu tihedusega",
    level = 4
  ),
  list( # K18
    goal = "eristab aktiivseid, keskmise aktiivsusega ja väheaktiivseid metalle nende asukoha järgi metallide pingereas ning uurib metallide aktiivsust",
    level = 3
  ),
  list( # K19
    goal = "eristab ioone neutraalsetest aatomitest ning selgitab ioonide tekkimist ja iooni laengut",
    level = 3
  ),
  list( # K20
    goal = "selgitab kovalentse, ioonilise ja metallilise sideme erinevust",
    level = 4
  ),
  list( # K21
    goal = "eristab valemi põhjal oksiide, happeid, hüdroksiide ja soolasid",
    level = 2
  ),
  list( # K22
    goal = "määrab aine valemi põhjal elementide oksüdatsiooniastmeid, koostab oksiidide nimetuste alusel valemeid ja valemite alusel nimetusi",
    level = 3
  ),
  list( # K23
    goal = "koostab hapete, hüdroksiidide ning soolade nimetuste alusel nende valemeid ja vastupidi",
    level = 3
  ),
  list( # K24
    goal = "mõistab reaktsioonivõrrandite tasakaalustamise põhimõtet",
    level = 2
  ),
  list( # K25
    goal = "korraldab lihtainete ühinemisreaktsioone hapnikuga ning koostab vastavaid reaktsioonivõrrandeid, toob näiteid igapäevaelus tuntumate oksiidide ja nende tähtsuse kohta",
    level = 3
  ),
  list( # K26
    goal = "uurib happeliste ja aluseliste oksiidide keemilisi omadusi: happeline oksiid + vesi, (tugevalt) aluseline oksiid + vesi, aluseline oksiid + hape, happeline oksiid + alus; koostab vastavate reaktsioonide võrrandeid",
    level = 3
  ),
  list( # K27
    goal = "lahendab reaktsioonivõrranditel põhinevaid arvutusülesandeid, lähtudes reaktsioonivõrrandite kordajatest (ainete moolsuhtest) ning reaktsioonis osalevate ainete hulkadest (moolides), tehes vajaduse korral ümberarvutusi ainehulga, massi ja (gaasi) ruumala vaheliste seoste alusel; põhjendab lahenduskäiku",
    level = 4
  ),
  list( # K28
    goal = "teab etanooli füsioloogilist toimet ja analüüsib sellega seotud probleeme igapäevaelus",
    level = 4
  ),
  list( # K29
    goal = "selgitab ja uurib keemiliste reaktsioonide soojusefekti",
    level = 4
  ),
  list( # K30
    goal = "analüüsib süsinikuühendite kasutusvõimalusi kütusena ning eristab taastuvaid ja taastumatuid energiaallikaid",
    level = 4
  ),
  list( # K31
    goal = "liigitab materjale hüdrofiilseks ja hüdrofoobseks",
    level = 2
  ),
  list( # K32
    goal = "seostab lahuste happelisi ja aluselisi omadusi nendes esinevate osakestega, hindab lahuse keskkonda indikaatoriga ja lahuse pH väärtuse järgi",
    level = 3
  ),
  list( # K33
    goal = "mõistab hapete ja aluste vastandlikkust, korraldab hapete ja aluste vahelisi reaktsioone ning koostab vastavaid reaktsioonivõrrandeid",
    level = 3
  ),
  list( # K34
    goal="toob näiteid tuntumate hapete, aluste ja soolade kasutamise kohta igapäevaelus",
    level=3
  ),
  list( # K35
    goal="selgitab tähtsamate anorgaaniliste ühendite leidumist looduses ja kasutamist argielus (väetised, vee karedus, ehitusmaterjalid)",
    level=4
  ),
  list( # K36
    goal="võrdleb ning põhjendab süsiniku lihtainete omadusi, võrdleb süsinikoksiidide omadusi",
    level=4
  ),
  list( # K37
    goal="eristab struktuurivalemi põhjal süsivesinikke, alkohole ja karboksüülhappeid",
    level=4
  ),
  list( # K38
    goal="tunneb struktuurivalemi järgi polümeeri",
    level=3
  ),
  list( # K39
    goal="iseloomustab tuntumaid süsinikuühenditel põhinevaid polümeerseid materjale (kiudained, plastid), analüüsib nende põhiomadusi, kasutamise võimalusi ja kasutamisega seonduvaid keskkonnaprobleeme",
    level=5
  ),
  list( # K40
    goal="mõistab elukeskkonda säästva suhtumise vajalikkust ning analüüsib keskkonna säästmise võimalusi",
    level=5
  ),
  list( # K41
    goal="mõistab sahhariidide, rasvade ja valkude rolli organismides, uurib nende omadusi ja sisaldust toiduainetes",
    level=4
  ),
  list( # K42
    goal="uurib etaanhappe keemilisi omadusi",
    level=4
  ),
  list( # K43
    goal="kirjeldab süsivesinike esinemisvorme looduses ja selgitab nende kasutusalasid",
    level=4
  ),
  list( # K44
    goal="hindab loogiliselt arvutustulemuste õigsust ning teeb arvutustulemuste põhjal järeldusi ja otsustusi",
    level=5
  ),
  list( # K45
    goal="teab keemilise saaste allikaid ja analüüsib saastumise tekkepõhjusi, saastumisest tingitud keskkonnaprobleeme (happesademed, raskmetallide ühendid, üleväetamine) ning võimalikke keskkonna säästmise meetmeid",
    level=6
  ),
  list( # K46
    goal="koostab reaktsioonivõrrandeid metallide ja hapete vaheliste reaktsioonide kohta",
    level=3
  ),
  list( # K47
    goal="seostab redoksreaktsioone keemiliste elementide oksüdatsiooniastmete muutumisega reaktsioonis, teab metallide käitumist keemilistes reaktsioonides redutseerijana ja hapniku käitumist oksüdeerijana",
    level=4
  ),
  list( # K48
    goal = "eristab füüsikalisi, keemilisi ja bioloogilisi nähtusi ning toob näiteid nendevaheliste seoste kohta",
    level = 4
  )
)

tasks <- list(
  list(
    goal = 1,
    level = 3,
    task = "Leia jooniselt \\@ref(fig:chemistry-tasks-safety) neli viga, kus eksitakse laboriohutusnõuete vastu ja kirjelda igaüht:\\leavevmode\\
    1. \\blank{Juuksed laiali.}\\leavevmode\\
    2. \\blank{Söömine.}\\leavevmode\\
    3. \\blank{Lekkimine.}\\leavevmode\\
    4. \\blank{Nuusutamine otse allikast.}"
  ),
  list(
    goal=1,
    level=3,
    task="Vaata pilti \\@ref(fig:chemistry-tasks-experiment-class) ja otsusta, milline loetelus olev lause väljendab ohutusreeglit, mida katset teinud õpilased ei järginud:
    \\begin{itemize}
      \\item[\\Circle] Valasid vett happesse.
      \\item[\\Circle] Jätsid anuma reaktsiooni järel sulgemata.
      \\item[\\Circle] Kasutasid liiga suuri ainete koguseid.
      \\item[\\Circle] Nuusutasid valesti reaktsioonis eralduvaid gaase.
      \\item[\\Circle] Kuumutasid anumat valesti.
      \\item[\\Circle] Valasid kokku hapet ja alust.
    \\end{itemize}
    "
  ),
  list(
    goal=2,
    level=3,
    task="Milline katsevahend on pildil \\@ref(fig:chemistry-tasks-experiment-class):
    \\begin{itemize}
      \\item[\\Circle] Katseklaas.
      \\item[\\Circle] Keeduklaas.
      \\item[\\Circle] Areomeeter.
      \\item[\\Circle] Pipett.
      \\item[\\Circle] Statiiv.
      \\item[\\Circle] Lehter.
      \\item[\\Circle] Kolb.
      \\item[\\Circle] Uhmer.
    \\end{itemize}
    "
  ),
  list(
    goal=3,
    level=3,
    task="Mis on söögiäädikas?
    \\begin{itemize}
      \\item[\\Circle] Suspensioon.
      \\item[\\Circle] Emulsioon.
      \\item[\\Circle] Tõeline lahus.
      \\item[\\Circle] Aerosool.
      \\item[\\Circle] Vaht.
      \\item[\\Circle] Tarre.
    \\end{itemize}
    "
  ),
  list(
    goal=3,
    level=3,
    task="Mis on kakaojook?
    \\begin{itemize}
      \\item[\\Circle] Suspensioon.
      \\item[\\Circle] Emulsioon.
      \\item[\\Circle] Tõeline lahus.
      \\item[\\Circle] Aerosool.
      \\item[\\Circle] Vaht.
      \\item[\\Circle] Tarre.
    \\end{itemize}
    "
  ),
  list(
    goal=3,
    level=3,
    task="Mis on piim?
    \\begin{itemize}
      \\item[\\Circle] Suspensioon.
      \\item[\\Circle] Emulsioon.
      \\item[\\Circle] Tõeline lahus.
      \\item[\\Circle] Aerosool.
      \\item[\\Circle] Vaht.
      \\item[\\Circle] Tarre.
    \\end{itemize}
    "
  ),
  list(
    goal=3,
    level=3,
    task="Mis on vahukoor?
    \\begin{itemize}
      \\item[\\Circle] Suspensioon.
      \\item[\\Circle] Emulsioon.
      \\item[\\Circle] Tõeline lahus.
      \\item[\\Circle] Aerosool.
      \\item[\\Circle] Vaht.
      \\item[\\Circle] Tarre.
    \\end{itemize}
    "
  ),
  list(
    goal=3,
    level=3,
    task="Mis on sült?
    \\begin{itemize}
      \\item[\\Circle] Suspensioon.
      \\item[\\Circle] Emulsioon.
      \\item[\\Circle] Tõeline lahus.
      \\item[\\Circle] Aerosool.
      \\item[\\Circle] Vaht.
      \\item[\\Circle] Tarre.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raud on
    \\begin{itemize}
      \\item[\\Square] metall.
      \\item[\\Square] mittemetall.
      \\item[\\Square] \\ce{Fe}.
    \\end{itemize}
        "
  ),
  list(
    goal=4,
    level=3,
    task="Raua periood:
    \\begin{itemize}
      \\item[\\Circle] 1.
      \\item[\\Circle] 2.
      \\item[\\Circle] 3.
      \\item[\\Circle] 4.
      \\item[\\Circle] 5.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raua rühm:
    \\begin{itemize}
      \\item[\\Circle] IIA.
      \\item[\\Circle] IIB.
      \\item[\\Circle] VIIIA.
      \\item[\\Circle] VIIIB.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raua prootonite arv:
    \\begin{itemize}
      \\item[\\Circle] 2.
      \\item[\\Circle] 3.
      \\item[\\Circle] 8.
      \\item[\\Circle] 14.
      \\item[\\Circle] 26.
      \\item[\\Circle] 30.
      \\item[\\Circle] 56.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raua neutronite arv:
    \\begin{itemize}
      \\item[\\Circle] 2.
      \\item[\\Circle] 3.
      \\item[\\Circle] 4.
      \\item[\\Circle] 8.
      \\item[\\Circle] 14.
      \\item[\\Circle] 26.
      \\item[\\Circle] 30.
      \\item[\\Circle] 56.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raua elektronite arv:
    \\begin{itemize}
      \\item[\\Circle] 2.
      \\item[\\Circle] 3.
      \\item[\\Circle] 4.
      \\item[\\Circle] 8.
      \\item[\\Circle] 14.
      \\item[\\Circle] 26.
      \\item[\\Circle] 30.
      \\item[\\Circle] 56.
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Raua aatom:
    \\begin{itemize}
      \\item[\\Circle] +26 | 2) 8) 14) 2).
      \\item[\\Circle] +26 | 2) 8) 14).
      \\item[\\Circle] +8 | 2) 8).
      \\item[\\Circle] +8 | 2).
      \\item[\\Circle] +8 | 2) 6).
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Roostetamisprotsessis raua ioon:
    \\begin{itemize}
      \\item[\\Circle] +26 | 2) 8) 14) 2).
      \\item[\\Circle] +26 | 2) 8) 14).
      \\item[\\Circle] +8 | 2) 8).
      \\item[\\Circle] +8 | 2).
      \\item[\\Circle] +8 | 2) 6).
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Roostetamisprotsessis hapniku ioon:
    \\begin{itemize}
      \\item[\\Circle] +26 | 2) 8) 14) 2).
      \\item[\\Circle] +26 | 2) 8) 14).
      \\item[\\Circle] +8 | 2) 8).
      \\item[\\Circle] +8 | 2).
      \\item[\\Circle] +8 | 2) 6).
    \\end{itemize}
    "
  ),
  list(
    goal=4,
    level=3,
    task="Hapniku aatom:
    \\begin{itemize}
      \\item[\\Circle] +26 | 2) 8) 14) 2).
      \\item[\\Circle] +26 | 2) 8) 14).
      \\item[\\Circle] +8 | 2) 8).
      \\item[\\Circle] +8 | 2).
      \\item[\\Circle] +8 | 2) 6).
    \\end{itemize}
    "
  ),
  list(
    goal=8,
    level=2,
    task="Vali kaks tunnust, mis näitavad, et pildil \\@ref(fig:chemistry-tasks-experiment-class) toimus keemiline reaktsioon:
    \\begin{itemize}
      \\item[\\Square] Valgusefektid.
      \\item[\\Square] Gaasi eraldumine.
      \\item[\\Square] Värvuse muutus.
      \\item[\\Square] Aine on vedelas olekus.
      \\item[\\Square] Sademe teke.
      \\item[\\Square] Aine asukoha muutus.
    \\end{itemize}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Mis on massiprotsent?
    \\begin{itemize}
      \\item[\\Circle] Aine, milles jaotuvad ühtlaselt teise aine väikesed osakesed.
      \\item[\\Circle] Aine, mille väikesed osakesed jaotuvad ühtlaselt teises aines.
      \\item[\\Circle] Suurus, mis näitab lahustunud aine massi protsenti lahuse kogumassis.
      \\item[\\Circle] Ühtlane ainete segu, mis koosneb lahustist ja lahustunud ainest.
    \\end{itemize}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Mis on lahus?
    \\begin{itemize}
      \\item[\\Circle] Aine, milles jaotuvad ühtlaselt teise aine väikesed osakesed.
      \\item[\\Circle] Aine, mille väikesed osakesed jaotuvad ühtlaselt teises aines.
      \\item[\\Circle] Suurus, mis näitab lahustunud aine massi protsenti lahuse kogumassis.
      \\item[\\Circle] Ühtlane ainete segu, mis koosneb lahustist ja lahustunud ainest.
    \\end{itemize}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Mis on lahusti?
    \\begin{itemize}
      \\item[\\Circle] Aine, milles jaotuvad ühtlaselt teise aine väikesed osakesed.
      \\item[\\Circle] Aine, mille väikesed osakesed jaotuvad ühtlaselt teises aines.
      \\item[\\Circle] Suurus, mis näitab lahustunud aine massi protsenti lahuse kogumassis.
      \\item[\\Circle] Ühtlane ainete segu, mis koosneb lahustist ja lahustunud ainest.
    \\end{itemize}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Mis on lahustunud aine?
    \\begin{itemize}
      \\item[\\Circle] Aine, milles jaotuvad ühtlaselt teise aine väikesed osakesed.
      \\item[\\Circle] Aine, mille väikesed osakesed jaotuvad ühtlaselt teises aines.
      \\item[\\Circle] Suurus, mis näitab lahustunud aine massi protsenti lahuse kogumassis.
      \\item[\\Circle] Ühtlane ainete segu, mis koosneb lahustist ja lahustunud ainest.
    \\end{itemize}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Vanaema oli ajakirjast lugenud, et kõrvetiste korral võiks kasutada süldi maitsestamiseks \\num{4}-\\unit{\\percent} äädikalahuse asemel \\num{2}-\\unit{\\percent} lahust. Vanamea lasi Annil mõõta kaaluga \\qty{200}{\\g} \\num{4}-\\unit{\\percent} äädikalahust. Ta palus arvutada, mitu grammi vett peab sellele lahusele lisama, et saada \\num{2}-\\unit{\\percent} äädikalahus. Kuidas saab anni leida äädika lahjendamiseks vajaliku vee massi?\\leavevmode\\
    
    Kirjuta tabelisse \\@ref(tab:chemistry-tasks-tables-solution) õige järjekord!"
  ),
  list(
    goal=11,
    level=3,
    task="Vanaema oli ajakirjast lugenud, et kõrvetiste korral võiks kasutada süldi maitsestamiseks \\num{4}-\\unit{\\percent} äädikalahuse asemel \\num{2}-\\unit{\\percent} lahust. Vanamea lasi Annil mõõta kaaluga \\qty{200}{\\g} \\num{4}-\\unit{\\percent} äädikalahust. Ta palus arvutada, mitu grammi vett peab sellele lahusele lisama, et saada \\num{2}-\\unit{\\percent} äädikalahus. Kirjuta, mis peab olema joonise \\@ref(fig:chemistry-tasks-content-of-solution) lahtrites enne lahjendamist alustades vasakult ülalt ja liikudes alla ning seejärel paremale:\\leavevmode\\
    \\blank{\\qty{96}{\\percent}}\\leavevmode\\
    \\blank{\\qty{192}{\\g}}\\leavevmode\\
    \\blank{\\qty{4}{\\percent}}\\leavevmode\\
    \\blank{\\qty{8}{\\g}}\\leavevmode\\
    \\blank{\\qty{100}{\\percent}}\\leavevmode\\
    \\blank{\\qty{200}{\\g}}
    "
  ),
  list(
    goal=11,
    level=3,
    task="Vanaema oli ajakirjast lugenud, et kõrvetiste korral võiks kasutada süldi maitsestamiseks \\num{4}-\\unit{\\percent} äädikalahuse asemel \\num{2}-\\unit{\\percent} lahust. Vanamea lasi Annil mõõta kaaluga \\qty{200}{\\g} \\num{4}-\\unit{\\percent} äädikalahust. Ta palus arvutada, mitu grammi vett peab sellele lahusele lisama, et saada \\num{2}-\\unit{\\percent} äädikalahus. Kirjuta, mis peab olema joonise \\@ref(fig:chemistry-tasks-content-of-solution-after) lahtrites pärast lahjendamist alustades vasakult ülalt ja liikudes alla ning seejärel paremale:\\leavevmode\\
    \\blank{\\qty{98}{\\percent}}\\leavevmode\\
    \\blank{\\qty{392}{\\g}}\\leavevmode\\
    \\blank{\\qty{2}{\\percent}}\\leavevmode\\
    \\blank{\\qty{8}{\\g}}\\leavevmode\\
    \\blank{\\qty{100}{\\percent}}\\leavevmode\\
    \\blank{\\qty{400}{\\g}}
    "
  ),
  list(
    goal=32,
    level=3,
    task="Avastusretkel keemialaboris märkas Dave, et hooletu minioni Kevini pükstele läks ainet, mille pudelile oli lisatud ohutusmärk (vaata joonist \\@ref(fig:chemistry-tasks-safety-label)). Kevin ei teadnud, millise ainega võiks tegemist olla. Dave leidis käsiraamatust, et selle ohumärgi nimetus on
    \\begin{itemize}
      \\item[\\Circle] rõhu all olev gaas.
      \\item[\\Circle] ohtlik keskkonnale.
      \\item[\\Circle] plahvatusohtlik.
      \\item[\\Circle] tuleohtlik.
      \\item[\\Circle] söövitav.
      \\item[\\Circle] oksüdeeriv.
      \\item[\\Circle] tõsine terviseoht.
    \\end{itemize}
    Seda märki kasutatakse anumatel, kus hoitakse väga happelisi aineid, nagu
    \\begin{itemize}
      \\item[\\Square] \\ce{NH3}.
      \\item[\\Square] \\ce{NaOH}.
      \\item[\\Square] \\ce{CO2}.
      \\item[\\Square] \\ce{HCl}.
      \\item[\\Square] \\ce{Mg}.
      \\item[\\Square] \\ce{CaO}.
      \\item[\\Square] \\ce{O2}.
      \\item[\\Square] \\ce{FeSO4}.
      \\item[\\Square] \\ce{Cu(OH)2}.
      \\item[\\Square] \\ce{AgNO3}.
      \\item[\\Square] vesinikkloriidhape.
    \\end{itemize}
    Samuti kasutatakse seda väga aluseliste ainete, nagu 
    \\begin{itemize}
      \\item[\\Square] \\ce{NaOH}
      \\item[\\Square] \\ce{SO3}
      \\item[\\Square] \\ce{HCl}
      \\item[\\Square] \\ce{Mg}
      \\item[\\Square] \\ce{H2S}
      \\item[\\Square] \\ce{Fe2O3}
      \\item[\\Square] \\ce{CaCO3}
      \\item[\\Square] \\ce{FeSO4}
      \\item[\\Square] \\ce{O2}
      \\item[\\Square] naatriumhüdroksiid
    \\end{itemize}
    tähistamiseks.\\leavevmode\\
    Dave leidis laborikapist lillad lakmuspaberid. Kui paber sattus Kevini pükste vastu, siis muutus selle värv punaseks. Minionid leidsid indikaatorpaberilt selgituse: $\\mathrm{p}(\\ce{H})>7$ - sellises keskkonnas on lakmus sinine,  $\\mathrm{p}(\\ce{H})=7$ - sellises keskkonnas on lakmus lilla,  $\\mathrm{p}(\\ce{H})<7$ - sellises keskkonnas on lakmus punane. Kollased mehikesed otsustasid, et Kevini pükstele on sattunud   
    \\begin{itemize}
      \\item[\\Square] neutraalset
      \\item[\\Square] aluselist
      \\item[\\Square] happelist
      \\item[\\Square] metallilist
      \\item[\\Square] happeline
    \\end{itemize}
    ainet. Selle aine neutraliseerimiseks pidid minionid pükse loputama kergelt 
    \\begin{itemize}
      \\item[\\Circle] metallilise
      \\item[\\Circle] happelise
      \\item[\\Circle] aluselise
      \\item[\\Circle] neutraalse
    \\end{itemize}
    ainega.
    "
  ),
  list(
    goal=33,
    level=3,
    task="Neutralisatsioonireaktsiooni lähteained on
    \\begin{itemize}
      \\item[\\Circle] \\ce{O2  +K}.
      \\item[\\Circle] \\ce{KCl +AgNO3}.
      \\item[\\Circle] \\ce{Cl +O2}.
      \\item[\\Circle] \\ce{K +HCl}.
      \\item[\\Circle] \\ce{KOH +HCL}.
      \\item[\\Circle] \\ce{KOH +CuSO4}.
    \\end{itemize}
    "
  ),
  list(
    goal=33,
    level=3,
    task="Neutralisatsioonireaktsiooni saadused on
    \\begin{itemize}
      \\item[\\Circle] sool + sool.
      \\item[\\Circle] sool + vesi.
      \\item[\\Circle] alus.
      \\item[\\Circle] sool + vesinik.
      \\item[\\Circle] hape + alus.
      \\item[\\Circle] hape.
      \\item[\\Circle] oksiid.
      \\item[\\Circle] sool + alus.
    \\end{itemize}
    "
  ),
  list(
    goal=47,
    level=4,
    task="Pildil \\@ref(fig:chemistry-tasks-Fe-ore) on
    \\begin{itemize}
      \\item[\\Circle] punane rauamaak (peamine koostisosa raud(III)oksiid), millest saab süsinikuga kuumutades puhta raua.
      \\item[\\Circle] rauast eseme reaktsioon soolhappega. Selle käigus eraldub mullikestena vesinik.
      \\item[\\Circle] raud(III)hüdroksiidi reaktsioon soolhappega ja selle käigus lahus neutraliseerub.
      \\item[\\Circle] puhas raud, milles raua osakese oküdatsiooniaste on 0.
      \\item[\\Circle] korrodeerunud rauast ese, mida katab raud(III)oksiid.
    \\end{itemize}
    "
  ),
  list(
    goal=47,
    level=4,
    task="Pildil \\@ref(fig:chemistry-tasks-Fe-nails) on
    \\begin{itemize}
      \\item[\\Circle] punane rauamaak (peamine koostisosa raud(III)oksiid), millest saab süsinikuga kuumutades puhta raua.
      \\item[\\Circle] rauast eseme reaktsioon soolhappega. Selle käigus eraldub mullikestena vesinik.
      \\item[\\Circle] raud(III)hüdroksiidi reaktsioon soolhappega ja selle käigus lahus neutraliseerub.
      \\item[\\Circle] puhas raud, milles raua osakese oküdatsiooniaste on 0.
      \\item[\\Circle] korrodeerunud rauast ese, mida katab raud(III)oksiid.
    \\end{itemize}
    "
  ),
  list(
    goal=47,
    level=4,
    task="Pildil \\@ref(fig:chemistry-tasks-Fe-reaction-with-metal) on
    \\begin{itemize}
      \\item[\\Circle] punane rauamaak (peamine koostisosa raud(III)oksiid), millest saab süsinikuga kuumutades puhta raua.
      \\item[\\Circle] rauast eseme reaktsioon soolhappega. Selle käigus eraldub mullikestena vesinik.
      \\item[\\Circle] raud(III)hüdroksiidi reaktsioon soolhappega ja selle käigus lahus neutraliseerub.
      \\item[\\Circle] puhas raud, milles raua osakese oküdatsiooniaste on 0.
      \\item[\\Circle] korrodeerunud rauast ese, mida katab raud(III)oksiid.
    \\end{itemize}
    "
  ),
  list(
    goal=47,
    level=4,
    task="Pildil \\@ref(fig:chemistry-tasks-Fe-corroded) on
    \\begin{itemize}
      \\item[\\Circle] punane rauamaak (peamine koostisosa raud(III)oksiid), millest saab süsinikuga kuumutades puhta raua.
      \\item[\\Circle] rauast eseme reaktsioon soolhappega. Selle käigus eraldub mullikestena vesinik.
      \\item[\\Circle] raud(III)hüdroksiidi reaktsioon soolhappega ja selle käigus lahus neutraliseerub.
      \\item[\\Circle] puhas raud, milles raua osakese oküdatsiooniaste on 0.
      \\item[\\Circle] korrodeerunud rauast ese, mida katab raud(III)oksiid.
    \\end{itemize}
    "
  ),
  list(
    goal=48,
    level=4,
    task="Füüsikaline nähtus:
    \\begin{itemize}
      \\item[\\Square] Vee keemine.
      \\item[\\Square] Raua roostetamine.
      \\item[\\Square] Organismi võitlus viirushaigusega.
      \\item[\\Square] Kuuma metalli sepistamine.
      \\item[\\Square] Udu teke.
      \\item[\\Square] Muna hüübimine praadimisel.
      \\item[\\Square] Piima hapnemine.
      \\item[\\Square] Lapse arenemine noorukiks.
      \\item[\\Square] Vee puhastamine filtreerimise teel.
      \\item[\\Square] Inimese kasvamine.
    \\end{itemize}
    "
  ),
  list(
    goal=48,
    level=4,
    task="Keemiline nähtus:
    \\begin{itemize}
      \\item[\\Square] Vee keemine.
      \\item[\\Square] Raua roostetamine.
      \\item[\\Square] Organismi võitlus viirushaigusega.
      \\item[\\Square] Kuuma metalli sepistamine.
      \\item[\\Square] Udu teke.
      \\item[\\Square] Muna hüübimine praadimisel.
      \\item[\\Square] Piima hapnemine.
      \\item[\\Square] Lapse arenemine noorukiks.
      \\item[\\Square] Vee puhastamine filtreerimise teel.
      \\item[\\Square] Inimese kasvamine.
    \\end{itemize}
    "
  ),
  list(
    goal=48,
    level=4,
    task="Bioloogiline nähtus:
    \\begin{itemize}
      \\item[\\Square] Vee keemine.
      \\item[\\Square] Raua roostetamine.
      \\item[\\Square] Organismi võitlus viirushaigusega.
      \\item[\\Square] Kuuma metalli sepistamine.
      \\item[\\Square] Udu teke.
      \\item[\\Square] Muna hüübimine praadimisel.
      \\item[\\Square] Piima hapnemine.
      \\item[\\Square] Lapse arenemine noorukiks.
      \\item[\\Square] Vee puhastamine filtreerimise teel.
      \\item[\\Square] Inimese kasvamine.
    \\end{itemize}
    "
  ),
  list(
    goal=48,
    level=4,
    task="Märgi tabelisse \\@ref(tab:chemistry-tasks-tables-occurrencies) vastav nähtuse liik ja näite tunnus järgnevast loetelust:
    \\begin{enumerate}
      \\item Lumi sulab veeks.
      \\item Inimene lisab poekotti ostetud kaupa.
      \\item Õpilane kõnni hommikul kodust kooli.
      \\item Kokk uhmerdab/peenestab maitseaineid.
      \\item Ahi soojeneb kütmisel.
      \\item Kumm pikeneb venimisel.
      \\item Tainas kerkib.
      \\item Raud roostetab.
      \\item Toit roiskub.
      \\item Toit kõrbeb põhja.
    \\end{enumerate}
    "
  ),
  list(
    goal=48,
    level=4,
    task="Märgi tabelisse \\@ref(tab:chemistry-tasks-tables-occurrency-of-many-types) igale reale, millise kahe nähtuse liigi tunnused nähtusel on järgnevast loetelust arvestades, et igas reas jääb üks lahter tühjaks:
    \\begin{enumerate}
      \\item Fotosünteesil tekib glükoos.
      \\item Lill areneb.
      \\item Tekivad \\ce{CO2} ja \\ce{H2O}.
      \\item Koogivorm soojeneb.
      \\item Vesi aurub.
      \\item Fotosüntees peatub.
      \\item Kuivas mullas puudub elu.
      \\item Taim valmistub puhkuseks.
      \\item Kook küpseb.
      \\item Parafiin sulab.
    \\end{enumerate}
    "
  )
)

dataframe_tasks <- do.call(rbind, lapply(tasks, as.data.frame, stringsAsFactors = FALSE))
number_goals <- length(goals)

librarian::shelf(c(
  "dplyr"
))

number_of_pupils <- 16

goals_in_use <- unique(dataframe_tasks$goal)
number_of_goals_in_use <- length(goals_in_use)

random_sample_df <- function(df, new_size) {
  base_size <- floor(new_size / nrow(df))  
  remaining <- new_size %% nrow(df)

  repeated_df <- df[rep(1:nrow(df), each = base_size), , drop = FALSE]

  extra_rows <- df[sample(1:nrow(df), remaining, replace = FALSE), , drop = FALSE]

  final_df <- rbind(repeated_df, extra_rows)
  final_df <- final_df[sample(1:nrow(final_df)), , drop = FALSE]

  return(final_df)
}

number_of_tasks_at_level_per_pupil <- 8 # 8
 
number_of_tasks <- nrow(dataframe_tasks)
df_segatud <- dataframe_tasks[sample(number_of_tasks), ]
arranged_sampled_tasks <- arrange(df_segatud, goal, level)

```

## Üks ülesanne õpilase kohta

```{r label="chemistry-list-of-tasks-one-per-pupil", echo=FALSE, results='asis'}

for (index_of_pupil in 1:number_of_pupils) {
  cat(paste("### Test: ", index_of_pupil, ". õpilane\n\n", sep = ""))

  for (index in 1:number_of_goals_in_use) {
    cat(paste(
      "**\\color[hsb]{0.",
      goals[[goals_in_use[index]]]$level - 1,
      ", 1, .75}{Õpiväljund:}** Õpilane ",
      goals[[goals_in_use[index]]]$goal,
      ".\n\n", 
      sep = ""
    ))

    for (index_of_levels in 1:6) {
      tasks_goal_level <- subset(arranged_sampled_tasks, index_of_levels == `level` & goals_in_use[index] == `goal`)
      number_of_tasks_goal_level <- nrow(tasks_goal_level)
      if (number_of_tasks_goal_level > 0) {
        
        cat(
          "**",
          index_of_levels,
          ". taseme ülesanne:** ",
          sep = ""
        )
      
        cat(tasks_goal_level[index_of_pupil %% number_of_tasks_goal_level + 1, ]$task, "\n\n", sep = "")
      }
    }

  }

}

# })

```

\clearpage

## Joonised

```{r label = "chemistry-tasks-safety", echo=FALSE, fig.cap = "Labori ohutusnõuete järgimine."}
include_external_graphics("rmd/keemia/parem-pilt-ohutusn6uded.png")

```

```{r label = "chemistry-tasks-safety-label", echo=FALSE, fig.cap = "Ohumärk."}
include_external_graphics("rmd/keemia/s__vitav0.PNG")

```

```{r label = "chemistry-tasks-experiment-class", echo=FALSE, fig.cap = "Katseklaas.", out.width=".92\\textwidth"}
include_external_graphics("rmd/keemia/katseklaas.jpg")

```

```{r label = "chemistry-tasks-content-of-solution", echo=FALSE, fig.cap = "Lahuse koostis."}
include_external_graphics("rmd/keemia/protsentjoonis_uuem_enne.jpg")

```

```{r label = "chemistry-tasks-content-of-solution-after", echo=FALSE, fig.cap = "Lahuse koostis pärast lahjendamist."}
include_external_graphics("rmd/keemia/protsentjoonis_uuem_p_rast.jpg")

```

```{r label = "chemistry-tasks-Fe-ore", echo=FALSE, fig.cap = "Raud või sellega seotu 1."}
include_external_graphics("rmd/keemia/rauamaak.jpg")

```

```{r label = "chemistry-tasks-Fe-nails", echo=FALSE, fig.cap = "Raud või sellega seotu 2."}
include_external_graphics("rmd/keemia/raudnaelad.jpg")

```

```{r label = "chemistry-tasks-Fe-reaction-with-metal", echo=FALSE, fig.cap = "Raud või sellega seotu 3."}
include_external_graphics("rmd/keemia/reaktsioon-metalliga.jpg")

```

```{r label = "chemistry-tasks-Fe-corroded", echo=FALSE, fig.cap = "Raud või sellega seotu 4."}
include_external_graphics("rmd/keemia/korrudeerunud-nael.jpg")

```

\clearpage

## Tabelid

```{r label="chemistry-tasks-tables-solution", echo=FALSE}
actions <- c(
  "Arvutab, mitu grammi on \\qty{200}{\\g} \\num{4}-\\unit{\\percent} äädikalahuses puhast äädikat.",
  "Lahutab saadud lahuse massist esialgse lahuse massi.",
  "Arvutab, mitu grammi on kogu lahust siis, kui äädikas moodustab lahusest \\qty{2}{\\percent}."
)

order_of_actions <- c(
  "\\blank{3}",
  "\\blank{3}",
  "\\blank{3}"
)

data <- data.frame(
  actions,
  order_of_actions
)

colnames(data) <- c(
  "Tegevus",
  "Mitmes?"
)

table <- print_table(
  table = data,
  caption = "Uue lahuse arvutamine."
) %>% landscape()

table

```

```{r label="chemistry-tasks-tables-occurrencies", echo=FALSE}
description <- c(
  "Muutub keha kuju.",
  "Muutub maitse.",
  "Muutuvad keha mõõtmed.",
  "Muutub keha temperatuur.",
  "Muutub värvus.",
  "Muutub aine olek.",
  "Eraldub gaas.",
  "Muutub keha mass.",
  "Muutub lõhn.",
  "Muutub keha asukoht."
)

number_of_items <- length(description)

type_of_occurrency <- rep(
  x="\\Circle Füüsikaline. \\Circle Keemiline.",
  number_of_items
)

example <- rep(x="\\blank{10}", number_of_items)

data <- data.frame(
  description,
  type_of_occurrency,
  example
)

colnames(data) <- c(
  "Kirjeldus",
  "Nähtuse liik",
  "Näide"
)

table <- print_table(
  table = data,
  caption = "Nähtuste jaotamine liikide kaupa näidetega."
)

table

```

```{r label="chemistry-tasks-tables-occurrency-of-many-types", echo=FALSE}
description <- c(
  "Küünal põleb.",
  "Kevadlilled hakkavad õitsema.",
  "Lehed muutuvad sügises värviliseks.",
  "Ahjus olev kook küpseb ja kerkib.",
  "Päike muudab maapinna kõvaks ja elutuks."
)

number_of_items <- length(description)

chemical <- rep(x="\\blank{10}", number_of_items)
physical <- rep(x="\\blank{10}", number_of_items)
biological <- rep(x="\\blank{10}", number_of_items)

data <- data.frame(
  description,
  chemical,
  physical,
  biological
)

colnames(data) <- c(
  "Nähtuse kirjeldus",
  "Keemilise nähtuse tunnus",
  "Füsikalise nähtuse tunnus",
  "Bioloogilise nähtuse tunnus"
)

table <- print_table(
  table = data,
  caption = "Nähtuste jaotamine liikide kaupa tunnustega."
) %>%
  column_spec(2, width="8em") %>%
  column_spec(3, width="8em") %>%
  column_spec(4, width="8em") %>%
  landscape()

table

```
